// openapi-fetch generates a typed fetch client from the OpenAPI `paths` type
// (web/src/lib/types/api.d.ts, generated by `make gen`), so every request/response
// shape here is checked against the backend contract at compile time.
import createClient from 'openapi-fetch';
import type { paths } from '$lib/types/api.d.ts';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080';
const DEV_PROPERTY_ID = import.meta.env.VITE_DEV_PROPERTY_ID || '';

export const api = createClient<paths>({
	baseUrl: API_BASE_URL,
	headers: DEV_PROPERTY_ID ? { 'X-Property-ID': DEV_PROPERTY_ID } : {}
});
