// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: availability.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getReservationItemsForPlanner = `-- name: GetReservationItemsForPlanner :many
SELECT ri.id as reservation_item_id,
  ri.reservation_id as reservation_id,
  ri.assigned_room_id,
  ri.booked_room_type_id,
  ri.stay_period,
  ri.base_rate_pence as stay_price_pence,
  ri.status as item_status,
  res.status as reservation_status,
  res.code as reservation_code,
  g.id as guest_id,
  g.first_name as guest_first_name,
  g.last_name as guest_last_name
FROM operations.reservation_items ri
  INNER JOIN operations.reservations res ON ri.reservation_id = res.id
  LEFT JOIN identity.guests g ON res.primary_guest_id = g.id
WHERE ri.deleted_at IS NULL
  AND res.deleted_at IS NULL
  AND ri.status NOT IN ('cancelled', 'archived')
  AND res.status NOT IN ('cancelled', 'archived')
  AND ri.stay_period && tstzrange(
    $1::timestamptz,
    $2::timestamptz,
    '[)'
  )
ORDER BY lower(ri.stay_period)
`

type GetReservationItemsForPlannerParams struct {
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

type GetReservationItemsForPlannerRow struct {
	ReservationItemID uuid.UUID                        `json:"reservation_item_id"`
	ReservationID     uuid.UUID                        `json:"reservation_id"`
	AssignedRoomID    uuid.NullUUID                    `json:"assigned_room_id"`
	BookedRoomTypeID  uuid.UUID                        `json:"booked_room_type_id"`
	StayPeriod        pgtype.Range[pgtype.Timestamptz] `json:"stay_period"`
	StayPricePence    int32                            `json:"stay_price_pence"`
	ItemStatus        OperationsReservationItemStatus  `json:"item_status"`
	ReservationStatus OperationsReservationStatus      `json:"reservation_status"`
	ReservationCode   pgtype.Text                      `json:"reservation_code"`
	GuestID           uuid.NullUUID                    `json:"guest_id"`
	GuestFirstName    pgtype.Text                      `json:"guest_first_name"`
	GuestLastName     pgtype.Text                      `json:"guest_last_name"`
}

func (q *Queries) GetReservationItemsForPlanner(ctx context.Context, arg GetReservationItemsForPlannerParams) ([]GetReservationItemsForPlannerRow, error) {
	rows, err := q.db.Query(ctx, getReservationItemsForPlanner, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReservationItemsForPlannerRow
	for rows.Next() {
		var i GetReservationItemsForPlannerRow
		if err := rows.Scan(
			&i.ReservationItemID,
			&i.ReservationID,
			&i.AssignedRoomID,
			&i.BookedRoomTypeID,
			&i.StayPeriod,
			&i.StayPricePence,
			&i.ItemStatus,
			&i.ReservationStatus,
			&i.ReservationCode,
			&i.GuestID,
			&i.GuestFirstName,
			&i.GuestLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomsForPlanner = `-- name: GetRoomsForPlanner :many
SELECT r.id as room_id,
  r.name as room_name,
  rt.code as room_type_code,
  rt.id as room_type_id
FROM inventory.rooms r
  INNER JOIN inventory.room_types rt ON r.room_type_id = rt.id
WHERE r.deleted_at IS NULL
ORDER BY rt.name,
  r.name
`

type GetRoomsForPlannerRow struct {
	RoomID       uuid.UUID `json:"room_id"`
	RoomName     string    `json:"room_name"`
	RoomTypeCode string    `json:"room_type_code"`
	RoomTypeID   uuid.UUID `json:"room_type_id"`
}

func (q *Queries) GetRoomsForPlanner(ctx context.Context) ([]GetRoomsForPlannerRow, error) {
	rows, err := q.db.Query(ctx, getRoomsForPlanner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomsForPlannerRow
	for rows.Next() {
		var i GetRoomsForPlannerRow
		if err := rows.Scan(
			&i.RoomID,
			&i.RoomName,
			&i.RoomTypeCode,
			&i.RoomTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
