// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: availability.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assertAvailabilityForRoomType = `-- name: AssertAvailabilityForRoomType :one
SELECT EXISTS (
  SELECT 1
  FROM inventory.room_inventory_ledger ril
  JOIN inventory.rooms r ON r.id = ril.room_id
  WHERE r.room_type_id = $1
    AND ril.calendar_date >= $2
    AND ril.calendar_date < $3
    AND ril.status = 'available'
  GROUP BY ril.room_id
  HAVING COUNT(*) = ($3::date - $2::date)
) AS is_available
`

type AssertAvailabilityForRoomTypeParams struct {
	RoomTypeID     pgtype.UUID `json:"room_type_id"`
	CalendarDate   pgtype.Date `json:"calendar_date"`
	CalendarDate_2 pgtype.Date `json:"calendar_date_2"`
}

func (q *Queries) AssertAvailabilityForRoomType(ctx context.Context, arg AssertAvailabilityForRoomTypeParams) (bool, error) {
	row := q.db.QueryRow(ctx, assertAvailabilityForRoomType, arg.RoomTypeID, arg.CalendarDate, arg.CalendarDate_2)
	var is_available bool
	err := row.Scan(&is_available)
	return is_available, err
}

const availableRoomTypesWithPrice = `-- name: AvailableRoomTypesWithPrice :many
WITH fully_available_rooms AS (
  SELECT
    r.id AS room_id,
    r.room_type_id
  FROM inventory.rooms r
  JOIN inventory.room_inventory_ledger ril
    ON ril.room_id = r.id
  WHERE ril.calendar_date >= $1::DATE
    AND ril.calendar_date < $2::DATE
    AND ril.status = 'available'
  GROUP BY r.id, r.room_type_id
  HAVING COUNT(*) = $3::INT
),
stay_price AS (
  SELECT
    ppg.room_type_id,
    SUM(ppg.base_price_pence)::int AS total_price_pence
  FROM pricing.daily_price_grid ppg
  WHERE ppg.rate_plan_id = $4::UUID
    AND ppg.calendar_date >= $1::DATE
    AND ppg.calendar_date < $2::DATE
  GROUP BY ppg.room_type_id
)
SELECT
  rt.id AS room_type_id,
  rt.code,
  rt.name,
  sp.total_price_pence,
  COUNT(far.room_id)::int AS available_rooms
FROM fully_available_rooms far
JOIN inventory.room_types rt
  ON rt.id = far.room_type_id
JOIN stay_price sp
  ON sp.room_type_id = rt.id
GROUP BY
  rt.id,
  rt.code,
  rt.name,
  sp.total_price_pence
ORDER BY rt.code
`

type AvailableRoomTypesWithPriceParams struct {
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	StayLength int32       `json:"stay_length"`
	RatePlanID pgtype.UUID `json:"rate_plan_id"`
}

type AvailableRoomTypesWithPriceRow struct {
	RoomTypeID      pgtype.UUID `json:"room_type_id"`
	Code            string      `json:"code"`
	Name            string      `json:"name"`
	TotalPricePence int32       `json:"total_price_pence"`
	AvailableRooms  int32       `json:"available_rooms"`
}

// param: ratePlanID UUID
// param: startDate DATE
// param: endDate DATE
// param: stayLength INT
func (q *Queries) AvailableRoomTypesWithPrice(ctx context.Context, arg AvailableRoomTypesWithPriceParams) ([]AvailableRoomTypesWithPriceRow, error) {
	rows, err := q.db.Query(ctx, availableRoomTypesWithPrice,
		arg.StartDate,
		arg.EndDate,
		arg.StayLength,
		arg.RatePlanID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailableRoomTypesWithPriceRow
	for rows.Next() {
		var i AvailableRoomTypesWithPriceRow
		if err := rows.Scan(
			&i.RoomTypeID,
			&i.Code,
			&i.Name,
			&i.TotalPricePence,
			&i.AvailableRooms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const canBookRoomType = `-- name: CanBookRoomType :one
SELECT COUNT(*) >= $4 AS can_book
FROM (
  SELECT ril.room_id
  FROM inventory.room_inventory_ledger ril
  JOIN inventory.rooms r ON r.id = ril.room_id
  WHERE r.room_type_id = $1
    AND ril.calendar_date >= $2
    AND ril.calendar_date < $3
    AND ril.status = 'available'
  GROUP BY ril.room_id
  HAVING COUNT(*) = ($3::date - $2::date)
) sub
`

type CanBookRoomTypeParams struct {
	RoomTypeID     pgtype.UUID `json:"room_type_id"`
	CalendarDate   pgtype.Date `json:"calendar_date"`
	CalendarDate_2 pgtype.Date `json:"calendar_date_2"`
	Column4        interface{} `json:"column_4"`
}

// params: room_type_id UUID, start_date DATE, end_date DATE, required_count INT
func (q *Queries) CanBookRoomType(ctx context.Context, arg CanBookRoomTypeParams) (bool, error) {
	row := q.db.QueryRow(ctx, canBookRoomType,
		arg.RoomTypeID,
		arg.CalendarDate,
		arg.CalendarDate_2,
		arg.Column4,
	)
	var can_book bool
	err := row.Scan(&can_book)
	return can_book, err
}

const countAvailableRoomsForRoomType = `-- name: CountAvailableRoomsForRoomType :one
SELECT COUNT(DISTINCT ril.room_id)::int
FROM inventory.room_inventory_ledger ril
JOIN inventory.rooms r ON r.id = ril.room_id
WHERE r.room_type_id = $1
  AND ril.calendar_date >= $2
  AND ril.calendar_date < $3
  AND ril.status = 'available'
GROUP BY ril.room_id
HAVING COUNT(*) = ($3::date - $2::date)
`

type CountAvailableRoomsForRoomTypeParams struct {
	RoomTypeID     pgtype.UUID `json:"room_type_id"`
	CalendarDate   pgtype.Date `json:"calendar_date"`
	CalendarDate_2 pgtype.Date `json:"calendar_date_2"`
}

func (q *Queries) CountAvailableRoomsForRoomType(ctx context.Context, arg CountAvailableRoomsForRoomTypeParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAvailableRoomsForRoomType, arg.RoomTypeID, arg.CalendarDate, arg.CalendarDate_2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listAvailableRoomTypes = `-- name: ListAvailableRoomTypes :many
WITH fully_available_rooms AS (
  SELECT
    r.id AS room_id,
    r.room_type_id
  FROM inventory.rooms r
  JOIN inventory.room_inventory_ledger ril
    ON ril.room_id = r.id
  WHERE ril.calendar_date >= $1
    AND ril.calendar_date < $2
    AND ril.status = 'available'
  GROUP BY r.id, r.room_type_id
  HAVING COUNT(*) = ($2::date - $1::date)
)
SELECT
  rt.id AS room_type_id,
  rt.code,
  rt.name,
  COUNT(far.room_id)::int AS available_rooms
FROM fully_available_rooms far
JOIN inventory.room_types rt
  ON rt.id = far.room_type_id
GROUP BY rt.id, rt.code, rt.name
ORDER BY rt.code
`

type ListAvailableRoomTypesParams struct {
	CalendarDate   pgtype.Date `json:"calendar_date"`
	CalendarDate_2 pgtype.Date `json:"calendar_date_2"`
}

type ListAvailableRoomTypesRow struct {
	RoomTypeID     pgtype.UUID `json:"room_type_id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	AvailableRooms int32       `json:"available_rooms"`
}

func (q *Queries) ListAvailableRoomTypes(ctx context.Context, arg ListAvailableRoomTypesParams) ([]ListAvailableRoomTypesRow, error) {
	rows, err := q.db.Query(ctx, listAvailableRoomTypes, arg.CalendarDate, arg.CalendarDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableRoomTypesRow
	for rows.Next() {
		var i ListAvailableRoomTypesRow
		if err := rows.Scan(
			&i.RoomTypeID,
			&i.Code,
			&i.Name,
			&i.AvailableRooms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roomTypeAvailabilityCalendar = `-- name: RoomTypeAvailabilityCalendar :many
SELECT
  ril.calendar_date,
  COUNT(*) FILTER (WHERE ril.status = 'available')::int AS available,
  COUNT(*) FILTER (WHERE ril.status = 'sold')::int AS sold,
  COUNT(*) FILTER (WHERE ril.status = 'maintenance')::int AS maintenance
FROM inventory.room_inventory_ledger ril
JOIN inventory.rooms r ON r.id = ril.room_id
WHERE r.room_type_id = $1
  AND ril.calendar_date BETWEEN $2 AND $3
GROUP BY ril.calendar_date
ORDER BY ril.calendar_date
`

type RoomTypeAvailabilityCalendarParams struct {
	RoomTypeID     pgtype.UUID `json:"room_type_id"`
	CalendarDate   pgtype.Date `json:"calendar_date"`
	CalendarDate_2 pgtype.Date `json:"calendar_date_2"`
}

type RoomTypeAvailabilityCalendarRow struct {
	CalendarDate pgtype.Date `json:"calendar_date"`
	Available    int32       `json:"available"`
	Sold         int32       `json:"sold"`
	Maintenance  int32       `json:"maintenance"`
}

func (q *Queries) RoomTypeAvailabilityCalendar(ctx context.Context, arg RoomTypeAvailabilityCalendarParams) ([]RoomTypeAvailabilityCalendarRow, error) {
	rows, err := q.db.Query(ctx, roomTypeAvailabilityCalendar, arg.RoomTypeID, arg.CalendarDate, arg.CalendarDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomTypeAvailabilityCalendarRow
	for rows.Next() {
		var i RoomTypeAvailabilityCalendarRow
		if err := rows.Scan(
			&i.CalendarDate,
			&i.Available,
			&i.Sold,
			&i.Maintenance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
