// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Action    string             `json:"action"`
	Entity    string             `json:"entity"`
	EntityID  pgtype.UUID        `json:"entity_id"`
	Changes   []byte             `json:"changes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DailyAvailability struct {
	ID            pgtype.UUID        `json:"id"`
	InventoryDate pgtype.Date        `json:"inventory_date"`
	RoomTypeID    pgtype.UUID        `json:"room_type_id"`
	TotalRooms    int32              `json:"total_rooms"`
	SoldCount     int32              `json:"sold_count"`
	DecomCount    int32              `json:"decom_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DailyRate struct {
	ID                pgtype.UUID        `json:"id"`
	StayDate          pgtype.Date        `json:"stay_date"`
	ReservationRoomID pgtype.UUID        `json:"reservation_room_id"`
	RatePlanID        pgtype.UUID        `json:"rate_plan_id"`
	GrossPrice        pgtype.Numeric     `json:"gross_price"`
	NetPrice          pgtype.Numeric     `json:"net_price"`
	Currency          string             `json:"currency"`
	RateNotes         pgtype.Text        `json:"rate_notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type DoNotMove struct {
	ID                pgtype.UUID        `json:"id"`
	ReservationRoomID pgtype.UUID        `json:"reservation_room_id"`
	Reason            pgtype.Text        `json:"reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Group struct {
	ID         pgtype.UUID        `json:"id"`
	GroupName  string             `json:"group_name"`
	GroupNotes pgtype.Text        `json:"group_notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Guest struct {
	ID             pgtype.UUID        `json:"id"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	Email          string             `json:"email"`
	IDDocumentData []byte             `json:"id_document_data"`
	MarketingOptIn pgtype.Bool        `json:"marketing_opt_in"`
	GuestNotes     pgtype.Text        `json:"guest_notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type GuestPreference struct {
	ID         pgtype.UUID `json:"id"`
	GuestID    pgtype.UUID `json:"guest_id"`
	Category   string      `json:"category"`
	Preference string      `json:"preference"`
}

type HousekeepingLog struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RoomID     pgtype.UUID        `json:"room_id"`
	StatusTo   string             `json:"status_to"`
	StatusFrom string             `json:"status_from"`
	Notes      pgtype.Text        `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Licence struct {
	ID               pgtype.UUID        `json:"id"`
	LicenceKey       string             `json:"licence_key"`
	OrganisationName string             `json:"organisation_name"`
	ContactEmail     string             `json:"contact_email"`
	LicenceNotes     pgtype.Text        `json:"licence_notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Property struct {
	ID            pgtype.UUID        `json:"id"`
	LicenceID     pgtype.UUID        `json:"licence_id"`
	Name          string             `json:"name"`
	Address       string             `json:"address"`
	PropertyNotes pgtype.Text        `json:"property_notes"`
	Timezone      string             `json:"timezone"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type PropertyAmenity struct {
	ID          pgtype.UUID        `json:"id"`
	PropertyID  pgtype.UUID        `json:"property_id"`
	Name        string             `json:"name"`
	ShortCode   string             `json:"short_code"`
	Description pgtype.Text        `json:"description"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RateAdjustment struct {
	ID          pgtype.UUID        `json:"id"`
	DailyRateID pgtype.UUID        `json:"daily_rate_id"`
	Type        string             `json:"type"`
	Amount      pgtype.Numeric     `json:"amount"`
	IsApproved  pgtype.Bool        `json:"is_approved"`
	Reason      pgtype.Text        `json:"reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RatePlan struct {
	ID                 pgtype.UUID        `json:"id"`
	PropertyID         pgtype.UUID        `json:"property_id"`
	Name               string             `json:"name"`
	CancellationPolicy pgtype.Text        `json:"cancellation_policy"`
	IsActive           pgtype.Bool        `json:"is_active"`
	IsBookable         pgtype.Bool        `json:"is_bookable"`
	Description        pgtype.Text        `json:"description"`
	ShortCode          string             `json:"short_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Reservation struct {
	ID               pgtype.UUID        `json:"id"`
	PropertyID       pgtype.UUID        `json:"property_id"`
	PrimaryGuestID   pgtype.UUID        `json:"primary_guest_id"`
	GroupID          pgtype.UUID        `json:"group_id"`
	BookingReference string             `json:"booking_reference"`
	Status           string             `json:"status"`
	Source           pgtype.Text        `json:"source"`
	ReservationNotes pgtype.Text        `json:"reservation_notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ReservationRoom struct {
	ID                   pgtype.UUID        `json:"id"`
	ReservationID        pgtype.UUID        `json:"reservation_id"`
	AssignedRoomID       pgtype.UUID        `json:"assigned_room_id"`
	CheckInDate          pgtype.Date        `json:"check_in_date"`
	CheckOutDate         pgtype.Date        `json:"check_out_date"`
	QuotedRate           pgtype.Numeric     `json:"quoted_rate"`
	ReservationRoomNotes pgtype.Text        `json:"reservation_room_notes"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Room struct {
	ID          pgtype.UUID        `json:"id"`
	PropertyID  pgtype.UUID        `json:"property_id"`
	RoomTypeID  pgtype.UUID        `json:"room_type_id"`
	RoomNumber  string             `json:"room_number"`
	Floor       pgtype.Int4        `json:"floor"`
	Status      string             `json:"status"`
	RoomNotes   pgtype.Text        `json:"room_notes"`
	IsTwinnable pgtype.Bool        `json:"is_twinnable"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RoomFeature struct {
	ID          pgtype.UUID        `json:"id"`
	RoomID      pgtype.UUID        `json:"room_id"`
	Name        string             `json:"name"`
	ShortCode   string             `json:"short_code"`
	Description pgtype.Text        `json:"description"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RoomType struct {
	ID                 pgtype.UUID        `json:"id"`
	PropertyID         pgtype.UUID        `json:"property_id"`
	Name               string             `json:"name"`
	ShortCode          string             `json:"short_code"`
	Description        pgtype.Text        `json:"description"`
	IsActive           pgtype.Bool        `json:"is_active"`
	IsAdmin            pgtype.Bool        `json:"is_admin"`
	MaxOccupancy       int32              `json:"max_occupancy"`
	BaseInventoryCount int32              `json:"base_inventory_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type RoomTypeAmenity struct {
	ID          pgtype.UUID        `json:"id"`
	RoomTypeID  pgtype.UUID        `json:"room_type_id"`
	Name        string             `json:"name"`
	ShortCode   string             `json:"short_code"`
	Description pgtype.Text        `json:"description"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	LicenceID    pgtype.UUID        `json:"licence_id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	Role         string             `json:"role"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
