// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pricing.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRate = `-- name: GetRate :one
SELECT COALESCE(
        dpg.base_price_pence,
        sr.base_price_pence,
        br.base_price_pence
    ) AS price_pence,
    COALESCE(
        dpg.min_los_restriction,
        sr.min_los_restriction,
        br.min_los_restriction,
        1
    ) AS min_los,
    COALESCE(
        dpg.max_los_restriction,
        sr.max_los_restriction,
        br.max_los_restriction,
        365
    ) AS max_los,
    CASE
        WHEN dpg.id IS NOT NULL THEN 'override'
        WHEN sr.id IS NOT NULL THEN 'seasonal'
        ELSE 'base'
    END::text AS source
FROM pricing.base_rates br
    LEFT JOIN pricing.seasonal_rates sr ON sr.property_id = br.property_id
    AND sr.room_type_id = br.room_type_id
    AND sr.rate_plan_id = br.rate_plan_id
    AND sr.day_of_week = EXTRACT(
        DOW
        FROM $1::date
    )::int
    AND sr.override_period @> $1::timestamptz
    AND sr.deleted_at IS NULL
    LEFT JOIN pricing.daily_price_grid dpg ON dpg.property_id = br.property_id
    AND dpg.room_type_id = br.room_type_id
    AND dpg.rate_plan_id = br.rate_plan_id
    AND dpg.calendar_date = $1
    AND dpg.deleted_at IS NULL
WHERE br.property_id = $2::uuid
    AND br.room_type_id = $3::uuid
    AND br.rate_plan_id = $4::uuid
    AND br.day_of_week = EXTRACT(
        DOW
        FROM $1::date
    )::int
    AND br.deleted_at IS NULL
`

type GetRateParams struct {
	CalendarDate pgtype.Date `json:"calendar_date"`
	PropertyID   uuid.UUID   `json:"property_id"`
	RoomTypeID   uuid.UUID   `json:"room_type_id"`
	RatePlanID   uuid.UUID   `json:"rate_plan_id"`
}

type GetRateRow struct {
	PricePence int32  `json:"price_pence"`
	MinLos     int32  `json:"min_los"`
	MaxLos     int32  `json:"max_los"`
	Source     string `json:"source"`
}

func (q *Queries) GetRate(ctx context.Context, arg GetRateParams) (GetRateRow, error) {
	row := q.db.QueryRow(ctx, getRate,
		arg.CalendarDate,
		arg.PropertyID,
		arg.RoomTypeID,
		arg.RatePlanID,
	)
	var i GetRateRow
	err := row.Scan(
		&i.PricePence,
		&i.MinLos,
		&i.MaxLos,
		&i.Source,
	)
	return i, err
}

const getRatesForRange = `-- name: GetRatesForRange :many
SELECT d.date::date AS calendar_date,
    br.room_type_id,
    br.rate_plan_id,
    COALESCE(
        dpg.base_price_pence,
        sr.base_price_pence,
        br.base_price_pence
    ) AS price_pence,
    COALESCE(
        dpg.min_los_restriction,
        sr.min_los_restriction,
        br.min_los_restriction,
        1
    ) AS min_los,
    COALESCE(
        dpg.max_los_restriction,
        sr.max_los_restriction,
        br.max_los_restriction,
        365
    ) AS max_los,
    CASE
        WHEN dpg.id IS NOT NULL THEN 'override'
        WHEN sr.id IS NOT NULL THEN 'seasonal'
        ELSE 'base'
    END AS source
FROM generate_series(
        $1::date,
        $2::date,
        '1 day'::interval
    ) AS d(date)
    CROSS JOIN pricing.base_rates br
    LEFT JOIN pricing.seasonal_rates sr ON sr.property_id = br.property_id
    AND sr.room_type_id = br.room_type_id
    AND sr.rate_plan_id = br.rate_plan_id
    AND sr.day_of_week = EXTRACT(
        DOW
        FROM d.date
    )::int
    AND sr.override_period @> d.date::timestamptz
    AND sr.deleted_at IS NULL
    LEFT JOIN pricing.daily_price_grid dpg ON dpg.property_id = br.property_id
    AND dpg.room_type_id = br.room_type_id
    AND dpg.rate_plan_id = br.rate_plan_id
    AND dpg.calendar_date = d.date
    AND dpg.deleted_at IS NULL
WHERE br.property_id = $3::uuid
    AND br.day_of_week = EXTRACT(
        DOW
        FROM d.date
    )::int
    AND br.deleted_at IS NULL
ORDER BY br.room_type_id,
    br.rate_plan_id,
    d.date
`

type GetRatesForRangeParams struct {
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	PropertyID uuid.UUID   `json:"property_id"`
}

type GetRatesForRangeRow struct {
	CalendarDate pgtype.Date   `json:"calendar_date"`
	RoomTypeID   uuid.NullUUID `json:"room_type_id"`
	RatePlanID   uuid.NullUUID `json:"rate_plan_id"`
	PricePence   int32         `json:"price_pence"`
	MinLos       int32         `json:"min_los"`
	MaxLos       int32         `json:"max_los"`
	Source       string        `json:"source"`
}

func (q *Queries) GetRatesForRange(ctx context.Context, arg GetRatesForRangeParams) ([]GetRatesForRangeRow, error) {
	rows, err := q.db.Query(ctx, getRatesForRange, arg.StartDate, arg.EndDate, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRatesForRangeRow
	for rows.Next() {
		var i GetRatesForRangeRow
		if err := rows.Scan(
			&i.CalendarDate,
			&i.RoomTypeID,
			&i.RatePlanID,
			&i.PricePence,
			&i.MinLos,
			&i.MaxLos,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
