// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateBookedDailyRate(ctx context.Context, arg CreateBookedDailyRateParams) (PricingBookedDailyRate, error)
	CreateReservationItem(ctx context.Context, arg CreateReservationItemParams) (OperationsReservationItem, error)
	GetRate(ctx context.Context, arg GetRateParams) (GetRateRow, error)
	GetRatePlans(ctx context.Context) ([]GetRatePlansRow, error)
	GetRatesForRange(ctx context.Context, arg GetRatesForRangeParams) ([]GetRatesForRangeRow, error)
	GetReservationItemsForPlanner(ctx context.Context, arg GetReservationItemsForPlannerParams) ([]GetReservationItemsForPlannerRow, error)
	GetRoomsForPlanner(ctx context.Context) ([]GetRoomsForPlannerRow, error)
	SetCurrentPropertyID(ctx context.Context, propertyID string) error
	UpdateReservationItem(ctx context.Context, arg UpdateReservationItemParams) (OperationsReservationItem, error)
}

var _ Querier = (*Queries)(nil)
