// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkLicenceExists = `-- name: CheckLicenceExists :one
SELECT EXISTS(SELECT 1 FROM licences WHERE id = $1) AS exists
`

func (q *Queries) CheckLicenceExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkLicenceExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createLicence = `-- name: CreateLicence :one
INSERT INTO licences (licence_key, organisation_name, contact_email, licence_notes) 
VALUES ($1, $2, $3, $4) RETURNING id, licence_key, organisation_name, contact_email, licence_notes, created_at, updated_at
`

type CreateLicenceParams struct {
	LicenceKey       string      `json:"licence_key"`
	OrganisationName string      `json:"organisation_name"`
	ContactEmail     string      `json:"contact_email"`
	LicenceNotes     pgtype.Text `json:"licence_notes"`
}

func (q *Queries) CreateLicence(ctx context.Context, arg CreateLicenceParams) (Licence, error) {
	row := q.db.QueryRow(ctx, createLicence,
		arg.LicenceKey,
		arg.OrganisationName,
		arg.ContactEmail,
		arg.LicenceNotes,
	)
	var i Licence
	err := row.Scan(
		&i.ID,
		&i.LicenceKey,
		&i.OrganisationName,
		&i.ContactEmail,
		&i.LicenceNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, first_name, last_name, is_active, licence_id, role) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, licence_id, username, email, password_hash, first_name, last_name, role, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	IsActive     pgtype.Bool `json:"is_active"`
	LicenceID    pgtype.UUID `json:"licence_id"`
	Role         string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.IsActive,
		arg.LicenceID,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LicenceID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLicence = `-- name: DeleteLicence :execresult
DELETE FROM licences WHERE id = $1
`

func (q *Queries) DeleteLicence(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteLicence, id)
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteUser, id)
}

const getLicenceByID = `-- name: GetLicenceByID :one
SELECT id, licence_key, organisation_name, contact_email, licence_notes, created_at, updated_at FROM licences WHERE id = $1
`

func (q *Queries) GetLicenceByID(ctx context.Context, id pgtype.UUID) (Licence, error) {
	row := q.db.QueryRow(ctx, getLicenceByID, id)
	var i Licence
	err := row.Scan(
		&i.ID,
		&i.LicenceKey,
		&i.OrganisationName,
		&i.ContactEmail,
		&i.LicenceNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLicenceByUserID = `-- name: GetLicenceByUserID :one
SELECT l.id, l.licence_key, l.organisation_name, l.contact_email, l.licence_notes, l.created_at, l.updated_at
FROM licences l
JOIN users u ON l.id = u.licence_id
WHERE u.id = $1 LIMIT 1
`

func (q *Queries) GetLicenceByUserID(ctx context.Context, id pgtype.UUID) (Licence, error) {
	row := q.db.QueryRow(ctx, getLicenceByUserID, id)
	var i Licence
	err := row.Scan(
		&i.ID,
		&i.LicenceKey,
		&i.OrganisationName,
		&i.ContactEmail,
		&i.LicenceNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, licence_id, username, email, password_hash, first_name, last_name, role, is_active, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LicenceID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersByLicenceID = `-- name: GetUsersByLicenceID :many
SELECT id, licence_id, username, email, password_hash, first_name, last_name, role, is_active, created_at, updated_at FROM users WHERE licence_id = $1
`

func (q *Queries) GetUsersByLicenceID(ctx context.Context, licenceID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByLicenceID, licenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.LicenceID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLicences = `-- name: ListLicences :many
SELECT id, licence_key, organisation_name, contact_email, licence_notes, created_at, updated_at FROM licences
`

func (q *Queries) ListLicences(ctx context.Context) ([]Licence, error) {
	rows, err := q.db.Query(ctx, listLicences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Licence
	for rows.Next() {
		var i Licence
		if err := rows.Scan(
			&i.ID,
			&i.LicenceKey,
			&i.OrganisationName,
			&i.ContactEmail,
			&i.LicenceNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, property_id, room_type_id, room_number, floor, status, room_notes, is_twinnable, created_at, updated_at FROM rooms
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.RoomTypeID,
			&i.RoomNumber,
			&i.Floor,
			&i.Status,
			&i.RoomNotes,
			&i.IsTwinnable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, licence_id, username, email, password_hash, first_name, last_name, role, is_active, created_at, updated_at FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.LicenceID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLicence = `-- name: UpdateLicence :one
UPDATE licences 
SET organisation_name = COALESCE($2, organisation_name),
    licence_key = COALESCE($3, licence_key),
    contact_email = COALESCE($4, contact_email),
    licence_notes = COALESCE($5, licence_notes),
    updated_at = NOW()
WHERE id = $1 RETURNING id, licence_key, organisation_name, contact_email, licence_notes, created_at, updated_at
`

type UpdateLicenceParams struct {
	ID               pgtype.UUID `json:"id"`
	OrganisationName string      `json:"organisation_name"`
	LicenceKey       string      `json:"licence_key"`
	ContactEmail     string      `json:"contact_email"`
	LicenceNotes     pgtype.Text `json:"licence_notes"`
}

func (q *Queries) UpdateLicence(ctx context.Context, arg UpdateLicenceParams) (Licence, error) {
	row := q.db.QueryRow(ctx, updateLicence,
		arg.ID,
		arg.OrganisationName,
		arg.LicenceKey,
		arg.ContactEmail,
		arg.LicenceNotes,
	)
	var i Licence
	err := row.Scan(
		&i.ID,
		&i.LicenceKey,
		&i.OrganisationName,
		&i.ContactEmail,
		&i.LicenceNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET 
    username = COALESCE($2, username),
    email = COALESCE($3, email),
    password_hash = COALESCE($4, password_hash),
    licence_id = COALESCE($5, licence_id),
    first_name = COALESCE($6, first_name),
    last_name = COALESCE($7, last_name),
    is_active = COALESCE($8, is_active),
    role = COALESCE($9, role),
    updated_at = NOW()
WHERE id = $1
RETURNING id, licence_id, username, email, password_hash, first_name, last_name, role, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Username     pgtype.Text `json:"username"`
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	LicenceID    pgtype.UUID `json:"licence_id"`
	FirstName    pgtype.Text `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
	IsActive     pgtype.Bool `json:"is_active"`
	Role         pgtype.Text `json:"role"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.LicenceID,
		arg.FirstName,
		arg.LastName,
		arg.IsActive,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LicenceID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
