// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateLicence(ctx context.Context, arg CreateLicenceParams) (Licence, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetLicenceByID(ctx context.Context, id pgtype.UUID) (Licence, error)
	GetLicenceByUserID(ctx context.Context, id pgtype.UUID) (Licence, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListLicences(ctx context.Context) ([]Licence, error)
	ListRooms(ctx context.Context) ([]Room, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
