// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate_plan.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRatePlans = `-- name: GetRatePlans :many
SELECT id,
    parent_rate_plan_id,
    name,
    code,
    description,
    currency_code
FROM pricing.rate_plans
WHERE deleted_at IS NULL
    AND is_active = true
`

type GetRatePlansRow struct {
	ID               uuid.UUID     `json:"id"`
	ParentRatePlanID uuid.NullUUID `json:"parent_rate_plan_id"`
	Name             string        `json:"name"`
	Code             string        `json:"code"`
	Description      pgtype.Text   `json:"description"`
	CurrencyCode     string        `json:"currency_code"`
}

func (q *Queries) GetRatePlans(ctx context.Context) ([]GetRatePlansRow, error) {
	rows, err := q.db.Query(ctx, getRatePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRatePlansRow
	for rows.Next() {
		var i GetRatePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentRatePlanID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.CurrencyCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
