// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBookedDailyRate = `-- name: CreateBookedDailyRate :one
INSERT INTO pricing.booked_daily_rates (
    property_id,
    reservation_item_id,
    calendar_date,
    rate_plan_id,
    base_price_pence,
    adjustment
  )
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
  )
RETURNING id, property_id, reservation_item_id, calendar_date, rate_plan_id, base_price_pence, adjustment, adjustment_approved, adjustment_approved_by_user_id, final_price_pence, created_at, updated_at, deleted_at
`

type CreateBookedDailyRateParams struct {
	PropertyID        uuid.NullUUID `json:"property_id"`
	ReservationItemID uuid.NullUUID `json:"reservation_item_id"`
	CalendarDate      pgtype.Date   `json:"calendar_date"`
	RatePlanID        uuid.NullUUID `json:"rate_plan_id"`
	BasePricePence    int32         `json:"base_price_pence"`
	Adjustment        []byte        `json:"adjustment"`
}

func (q *Queries) CreateBookedDailyRate(ctx context.Context, arg CreateBookedDailyRateParams) (PricingBookedDailyRate, error) {
	row := q.db.QueryRow(ctx, createBookedDailyRate,
		arg.PropertyID,
		arg.ReservationItemID,
		arg.CalendarDate,
		arg.RatePlanID,
		arg.BasePricePence,
		arg.Adjustment,
	)
	var i PricingBookedDailyRate
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.ReservationItemID,
		&i.CalendarDate,
		&i.RatePlanID,
		&i.BasePricePence,
		&i.Adjustment,
		&i.AdjustmentApproved,
		&i.AdjustmentApprovedByUserID,
		&i.FinalPricePence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createReservationItem = `-- name: CreateReservationItem :one
INSERT INTO operations.reservation_items (
    property_id,
    reservation_id,
    booked_room_type_id,
    assigned_room_id,
    rate_plan_id,
    stay_period,
    adults_count,
    children_count,
    status
  )
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    tstzrange(
      $6::timestamptz,
      $7::timestamptz,
      '[)'
    ),
    $8,
    $9,
    'booked'
  )
RETURNING id, property_id, reservation_id, booked_room_type_id, assigned_room_id, rate_plan_id, stay_period, base_rate_pence, adults_count, children_count, status, created_at, updated_at, deleted_at, guest_id
`

type CreateReservationItemParams struct {
	PropertyID       uuid.NullUUID      `json:"property_id"`
	ReservationID    uuid.UUID          `json:"reservation_id"`
	BookedRoomTypeID uuid.UUID          `json:"booked_room_type_id"`
	AssignedRoomID   uuid.NullUUID      `json:"assigned_room_id"`
	RatePlanID       uuid.NullUUID      `json:"rate_plan_id"`
	CheckIn          pgtype.Timestamptz `json:"check_in"`
	CheckOut         pgtype.Timestamptz `json:"check_out"`
	AdultsCount      int32              `json:"adults_count"`
	ChildrenCount    int32              `json:"children_count"`
}

func (q *Queries) CreateReservationItem(ctx context.Context, arg CreateReservationItemParams) (OperationsReservationItem, error) {
	row := q.db.QueryRow(ctx, createReservationItem,
		arg.PropertyID,
		arg.ReservationID,
		arg.BookedRoomTypeID,
		arg.AssignedRoomID,
		arg.RatePlanID,
		arg.CheckIn,
		arg.CheckOut,
		arg.AdultsCount,
		arg.ChildrenCount,
	)
	var i OperationsReservationItem
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.ReservationID,
		&i.BookedRoomTypeID,
		&i.AssignedRoomID,
		&i.RatePlanID,
		&i.StayPeriod,
		&i.BaseRatePence,
		&i.AdultsCount,
		&i.ChildrenCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GuestID,
	)
	return i, err
}

const updateReservationItem = `-- name: UpdateReservationItem :one
UPDATE operations.reservation_items
SET assigned_room_id = COALESCE(
    $1::uuid,
    assigned_room_id
  ),
  booked_room_type_id = COALESCE(
    $2::uuid,
    booked_room_type_id
  ),
  stay_period = COALESCE(
    tstzrange(
      $3::timestamptz,
      $4::timestamptz,
      '[)'
    ),
    stay_period
  ),
  status = COALESCE(
    $5::operations.reservation_item_status,
    status
  ),
  updated_at = NOW()
WHERE id = $6::uuid
  AND deleted_at IS NULL
RETURNING id, property_id, reservation_id, booked_room_type_id, assigned_room_id, rate_plan_id, stay_period, base_rate_pence, adults_count, children_count, status, created_at, updated_at, deleted_at, guest_id
`

type UpdateReservationItemParams struct {
	AssignedRoomID    uuid.NullUUID                       `json:"assigned_room_id"`
	BookedRoomTypeID  uuid.NullUUID                       `json:"booked_room_type_id"`
	CheckInDate       pgtype.Timestamptz                  `json:"check_in_date"`
	CheckOutDate      pgtype.Timestamptz                  `json:"check_out_date"`
	Status            NullOperationsReservationItemStatus `json:"status"`
	ReservationItemID uuid.UUID                           `json:"reservation_item_id"`
}

func (q *Queries) UpdateReservationItem(ctx context.Context, arg UpdateReservationItemParams) (OperationsReservationItem, error) {
	row := q.db.QueryRow(ctx, updateReservationItem,
		arg.AssignedRoomID,
		arg.BookedRoomTypeID,
		arg.CheckInDate,
		arg.CheckOutDate,
		arg.Status,
		arg.ReservationItemID,
	)
	var i OperationsReservationItem
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.ReservationID,
		&i.BookedRoomTypeID,
		&i.AssignedRoomID,
		&i.RatePlanID,
		&i.StayPeriod,
		&i.BaseRatePence,
		&i.AdultsCount,
		&i.ChildrenCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.GuestID,
	)
	return i, err
}
