basePath: /v1
host: localhost:8080
info:
  contact:
    email: support@yop-pms.com
    name: API Support
    url: http://www.yop-pms.com/support
  description: This is the backend API documentation for Yop PMS.
  title: Yop PMS Backend API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
