/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/healthz': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Server Health
		 * @description Check if the server, database, and redis are alive
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['cmd_server.HealthResponse'];
					};
				};
				/** @description Service Unavailable */
				503: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['cmd_server.HealthResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		'cmd_server.HealthResponse': {
			/** @example Server is running */
			message?: string;
			services?: {
				[key: string]: components['schemas']['cmd_server.ServiceHealth'];
			};
			/** @example ok */
			status?: string;
			/** @example 1.0.0 */
			version?: string;
		};
		'cmd_server.ServiceHealth': {
			error?: string;
			/** @example 5ms */
			latency?: string;
			/** @example ok */
			status?: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
