/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Server Health
         * @description Check if the server, database, and redis are alive
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["cmd_server.HealthResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["cmd_server.HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reservations
         * @description Cursor-paginated list of reservations for the property.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by status */
                    status?: string;
                    /** @description Page size (default 50) */
                    limit?: number;
                };
                header: {
                    /** @description Property UUID */
                    "X-Property-ID": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_booking.ReservationResponse"][];
                    };
                };
                /** @description Invalid X-Property-ID or query params */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create reservation
         * @description Create a new reservation with one or more room items.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Property UUID */
                    "X-Property-ID": string;
                };
                path?: never;
                cookie?: never;
            };
            /** @description Reservation payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_booking.CreateReservationInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_booking.ReservationResponse"];
                    };
                };
                /** @description Invalid request body or X-Property-ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"];
                    };
                };
                /** @description Resource conflict (e.g. duplicate, version mismatch) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"];
                    };
                };
                /** @description Validation failed */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"];
                    };
                };
                /** @description Feature not implemented */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get reservation
         * @description Fetch a single reservation by ID.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated: items,guest,none */
                    include?: string;
                };
                header: {
                    /** @description Property UUID */
                    "X-Property-ID": string;
                };
                path: {
                    /** @description Reservation UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_booking.ReservationResponse"];
                    };
                };
                /** @description Invalid ID or X-Property-ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"];
                    };
                };
                /** @description Reservation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to real-time SSE events
         * @description Opens a Server-Sent Events stream for real-time updates
         */
        get: {
            parameters: {
                query: {
                    /** @description Property UUID (must match authenticated session) */
                    property_id: string;
                };
                header: {
                    /** @description Property UUID from authenticated session */
                    "X-Property-ID": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE event stream — one ChangeEvent per line */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description property_id query parameter is required or invalid UUID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"];
                    };
                };
                /** @description No authenticated session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"];
                    };
                };
                /** @description Property access denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"];
                    };
                };
                /** @description SSE at capacity */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "cmd_server.HealthResponse": {
            /** @example Server is running */
            message?: string;
            services?: {
                [key: string]: components["schemas"]["cmd_server.ServiceHealth"];
            };
            /** @example ok */
            status?: string;
            /** @example 1.0.0 */
            version?: string;
        };
        "cmd_server.ServiceHealth": {
            error?: string;
            /** @example 5ms */
            latency?: string;
            /** @example ok */
            status?: string;
        };
        "github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError": {
            /** @enum {string} */
            code?: "NOT_FOUND" | "BAD_REQUEST" | "CONFLICT" | "INTERNAL_ERROR" | "UNPROCESSABLE_ENTITY";
            message?: string;
            suggestions?: string[];
        };
        "github_com_lexxcode1_yop-pms_internal_platform_types.ISO8601Date": {
            "time.Time"?: string;
        };
        "internal_booking.CancellationIntent": {
            cancelled_by_user_id?: string;
            /** @example Loyalty member */
            fee_override_reason?: string;
            /** @example 5000 */
            fee_pence?: number;
            /** @example guest_request */
            reason_code?: string;
            /** @example original */
            refund_action?: components["schemas"]["internal_booking.RefundAction"];
            /** @example false */
            waive_fee?: boolean;
        };
        "internal_booking.CreateReservationInput": Record<string, never>;
        "internal_booking.GuestInlinePayload": {
            /** @example jane.doe@example.com */
            email?: string;
            /** @example Jane */
            first_name?: string;
            /** @example 00000000-0000-0000-0000-000000000000 */
            id?: string;
            /** @example Doe */
            last_name?: string;
            /** @example +441234567890 */
            phone?: string;
        };
        "internal_booking.GuestResponse": {
            /** @example jane@example.com */
            email?: string;
            /** @example Jane */
            first_name?: string;
            /** @example 00000000-0000-0000-0000-000000000000 */
            id?: string;
            /** @example Doe */
            last_name?: string;
            /** @example +441234567890 */
            phone?: string;
            property_id?: string;
        };
        "internal_booking.ItemResponse": {
            /** @example 2 */
            adults_count?: number;
            /** @example 00000000-0000-0000-0000-000000000000 */
            assigned_room_id?: string;
            /** @example 15000 */
            base_rate_pence?: number;
            /** @example 00000000-0000-0000-0000-000000000000 */
            booked_room_type_id?: string;
            /** @example 0 */
            children_count?: number;
            created_at?: string;
            deleted_at?: string;
            /** @example false */
            do_not_move?: boolean;
            /** @example 00000000-0000-0000-0000-000000000000 */
            guest_id?: string;
            /** @example 00000000-0000-0000-0000-000000000000 */
            id?: string;
            /** @example 00000000-0000-0000-0000-000000000000 */
            property_id?: string;
            /** @example 00000000-0000-0000-0000-000000000000 */
            rate_plan_id?: string;
            /** @example 00000000-0000-0000-0000-000000000000 */
            reservation_id?: string;
            /** @example booked */
            status?: components["schemas"]["internal_booking.ItemStatus"];
            stay_period?: string;
            updated_at?: string;
            /** @example 1 */
            version?: number;
        };
        /** @enum {string} */
        "internal_booking.ItemStatus": "booked" | "checked_in" | "checked_out" | "no_show" | "overstay" | "cancelled" | "archived";
        /** @enum {string} */
        "internal_booking.RefundAction": "none" | "original" | "credit";
        "internal_booking.ReservationResponse": {
            cancellation_intent?: components["schemas"]["internal_booking.CancellationIntent"];
            /** @example RES-111213 */
            code?: string;
            created_at?: string;
            deleted_at?: string;
            expires_at?: string;
            /** @example 00000000-0000-0000-0000-000000000000 */
            group_id?: string;
            guest?: components["schemas"]["internal_booking.GuestResponse"];
            /** @example 00000000-0000-0000-0000-000000000000 */
            id?: string;
            items?: components["schemas"]["internal_booking.ItemResponse"][];
            /** @example Guest requested top floor */
            notes?: string;
            /** @example 00000000-0000-0000-0000-000000000000 */
            primary_guest_id?: string;
            /** @example 00000000-0000-0000-0000-000000000000 */
            property_id?: string;
            /** @example 42 */
            sequential?: number;
            /** @example internal */
            source?: components["schemas"]["internal_booking.ReservationSource"];
            /** @example hold */
            status?: components["schemas"]["internal_booking.ReservationStatus"];
            stay_period_envelope?: string;
            /** @example 00000000-0000-0000-0000-000000000000 */
            travel_agent_id?: string;
            updated_at?: string;
            /** @example 1 */
            version?: number;
        };
        /** @enum {string} */
        "internal_booking.ReservationSource": "website" | "internal" | "ota";
        /** @enum {string} */
        "internal_booking.ReservationStatus": "hold" | "confirmed" | "checked_in" | "checked_out" | "pending_cancellation" | "cancelled" | "archived";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
