// Auto-generated by 'make gen-constraints'. Do not edit manually.
// Run 'make gen-constraints' after any schema migration.

export const CONSTRAINTS = {} as const;

export type ConstraintTable = keyof typeof CONSTRAINTS;
