// Auto-generated by 'make gen-constraints'. Do not edit manually.
// Run 'make gen-constraints' after any schema migration.

export const CONSTRAINTS = {
	'auth.audit_logs': {
		fields: {
			action: { required: true },
			changes: { required: true },
			entity: { required: true },
			entity_id: { required: true },
			property_id: { required: true }
		},
		notes: ["audit_logs_changes_check: jsonb_typeof(changes) \u003D \'object\'::text"]
	},
	'auth.users': {
		fields: {
			email: { required: true, maxLength: 100 },
			first_name: { required: true, maxLength: 50 },
			is_active: { required: true },
			last_name: { required: true, maxLength: 50 },
			licence_id: { required: true },
			role: { required: true },
			username: { required: true, maxLength: 20, pattern: /^[a-zA-Z0-9_]+$/ }
		}
	},
	'finance.folio_transactions': {
		fields: {
			description: { maxLength: 250 },
			folio_id: { required: true },
			net_unit_price_pence: { required: true },
			property_id: { required: true },
			quantity: { required: true, min: 1 },
			status: { required: true },
			tax_rate_snapshot: { required: true }
		}
	},
	'finance.folios': {
		fields: {
			balance_pence: { required: true },
			folio_part: { required: true },
			property_id: { required: true }
		}
	},
	'finance.invoices': {
		fields: {
			billing_address: { required: true, maxLength: 250 },
			due_date: { required: true },
			fiscal_sequential: { required: true },
			fiscal_year: { required: true },
			is_pro_forma: { required: true },
			issue_date: { required: true },
			property_code: { required: true, maxLength: 4, min: 3 },
			property_id: { required: true }
		}
	},
	'finance.ledger_codes': {
		fields: {
			code: { required: true, maxLength: 50 },
			description: { maxLength: 250 },
			property_id: { required: true }
		}
	},
	'finance.tax_rules': {
		fields: {
			description: { maxLength: 250 },
			is_tax_inclusive: { required: true },
			name: { required: true, maxLength: 50 },
			property_id: { required: true },
			tax_percentage: { required: true }
		},
		notes: [
			'tax_rules_tax_percentage_check: (tax_percentage \u003E\u003D (0)::numeric) AND (tax_percentage \u003C\u003D (75)::numeric)'
		]
	},
	'identity.company_profiles': {
		fields: {
			billing_address: { maxLength: 300 },
			company_name: { required: true, maxLength: 50, min: 2 },
			company_notes: { maxLength: 1500 },
			contact_email: { maxLength: 100 },
			contact_phone: { maxLength: 20 },
			has_credit_facility: { required: true },
			property_id: { required: true }
		}
	},
	'identity.guests': {
		fields: {
			email: { maxLength: 100 },
			first_name: { required: true, maxLength: 50 },
			is_anonymised: { required: true },
			last_name: { required: true, maxLength: 50 },
			marketing_opt_in: { required: true },
			notes: { maxLength: 1500 },
			phone_number: { maxLength: 20 },
			property_id: { required: true }
		}
	},
	'identity.identity_docs': {
		fields: {
			doc_type: { required: true },
			encrypted_doc_number: { required: true, maxLength: 100 },
			guest_id: { required: true },
			issuing_country: { maxLength: 100 },
			property_id: { required: true }
		}
	},
	'identity.travel_agents': {
		fields: {
			agency_notes: { maxLength: 1000 },
			commission_percent: { required: true },
			contact_email: { maxLength: 100 },
			contact_phone: { maxLength: 20 },
			iata_code: { maxLength: 50 },
			name: { required: true, maxLength: 100 },
			property_id: { required: true }
		},
		notes: [
			'travel_agents_commission_percent_check: (commission_percent \u003E\u003D (0)::numeric) AND (commission_percent \u003C\u003D (75)::numeric)'
		]
	},
	'inventory.housekeeping_logs': {
		fields: {
			notes: { maxLength: 250 },
			property_id: { required: true },
			room_id: { required: true },
			status_from: { required: true },
			status_to: { required: true }
		},
		notes: [
			'housekeeping_logs_check: status_to \u003C\u003E status_from',
			'housekeeping_logs_check: status_to \u003C\u003E status_from'
		]
	},
	'inventory.maintenance_blocks': {
		fields: {
			block_period: { required: true, validRange: true },
			property_id: { required: true },
			reason: { required: true, maxLength: 150 },
			room_id: { required: true },
			type: { required: true }
		},
		notes: [
			'GIST maintenance_blocks_room_id_block_period_excl: EXCLUDE USING gist (room_id WITH \u003D, block_period WITH \u0026\u0026) WHERE ((deleted_at IS NULL))'
		]
	},
	'inventory.room_inventory_ledger': {
		fields: {
			calendar_date: { required: true },
			property_id: { required: true },
			room_id: { required: true },
			status: { required: true }
		},
		notes: [
			"room_inventory_ledger_check: ((status \u003D \'sold\'::inventory.inventory_status) AND (reservation_id IS NOT NULL)) OR (status \u003C\u003E \'sold\'::inventory.inventory_status)",
			"room_inventory_ledger_check: ((status \u003D \'sold\'::inventory.inventory_status) AND (reservation_id IS NOT NULL)) OR (status \u003C\u003E \'sold\'::inventory.inventory_status)",
			"room_inventory_ledger_check1: ((status \u003D \'on_hold\'::inventory.inventory_status) AND (checkout_session_id IS NOT NULL)) OR (status \u003C\u003E \'on_hold\'::inventory.inventory_status)",
			"room_inventory_ledger_check1: ((status \u003D \'on_hold\'::inventory.inventory_status) AND (checkout_session_id IS NOT NULL)) OR (status \u003C\u003E \'on_hold\'::inventory.inventory_status)"
		]
	},
	'inventory.room_types': {
		fields: {
			code: { required: true, maxLength: 10 },
			max_occupancy: { required: true, min: 1 },
			min_occupancy: { required: true, min: 1 },
			name: { required: true, maxLength: 75 },
			property_id: { required: true },
			std_occupancy: { required: true, min: 1 }
		}
	},
	'inventory.rooms': {
		fields: {
			housekeeping_status: { required: true },
			name: { required: true, maxLength: 75 },
			occupancy_status: { required: true },
			property_id: { required: true }
		}
	},
	'operations.amenities': {
		fields: {
			description: { maxLength: 250 },
			is_active: { required: true },
			name: { required: true, maxLength: 100 },
			property_id: { required: true },
			short_code: { maxLength: 10, pattern: /^[A-Z0-9_/]{2,5}$/ }
		}
	},
	'operations.checkout_sessions': {
		fields: {
			expires_at: { required: true },
			idempotency_key: { maxLength: 255 },
			payment_intent_id: { required: true, maxLength: 255 },
			property_id: { required: true },
			reservation_id: { required: true },
			status: { required: true }
		}
	},
	'operations.licences': {
		fields: {
			contact_email: { required: true },
			is_active: { required: true },
			licence_key: { required: true, pattern: /^YOP-\d{5}$/ },
			licence_notes: { maxLength: 1500 },
			organisation_name: { required: true, maxLength: 50 }
		}
	},
	'operations.properties': {
		fields: {
			address: { required: true, maxLength: 250 },
			is_active: { required: true },
			licence_id: { required: true },
			name: { required: true, maxLength: 50 },
			property_notes: { maxLength: 1500 },
			timezone: { required: true, maxLength: 100 }
		}
	},
	'operations.reservation_groups': {
		fields: {
			name: { maxLength: 50 },
			notes: { maxLength: 2500 },
			property_id: { required: true },
			sequential: { required: true }
		}
	},
	'operations.reservation_items': {
		fields: {
			adults_count: { required: true, min: 1 },
			base_rate_pence: { required: true, min: 0 },
			booked_room_type_id: { required: true },
			children_count: { required: true },
			property_id: { required: true },
			reservation_id: { required: true },
			status: { required: true },
			stay_period: { required: true, validRange: true }
		},
		notes: [
			'GIST reservation_items_assigned_room_id_stay_period_excl: EXCLUDE USING gist (assigned_room_id WITH \u003D, stay_period WITH \u0026\u0026) WHERE (((deleted_at IS NULL) AND (assigned_room_id IS NOT NULL)))'
		]
	},
	'operations.reservations': {
		fields: {
			notes: { maxLength: 2500 },
			primary_guest_id: { required: true },
			property_id: { required: true },
			sequential: { required: true },
			source: { required: true },
			status: { required: true },
			version: { required: true }
		}
	},
	'pricing.base_rates': {
		fields: {
			base_price_pence: { required: true },
			day_of_week: { required: true, min: 0 },
			min_los_restriction: { min: 1 },
			property_id: { required: true },
			rate_plan_id: { required: true },
			room_type_id: { required: true }
		},
		comparisons: [
			{ field: 'max_los_restriction', operator: '>', other: 'min_los_restriction' },
			{ field: 'max_los_restriction', operator: '>', other: 'min_los_restriction' }
		]
	},
	'pricing.booked_daily_rates': {
		fields: {
			adjustment: {
				jsonb: {
					reason: { required: true },
					type: { required: true },
					value: { required: true }
				}
			},
			adjustment_approved: { required: true },
			base_price_pence: { required: true, min: 0 },
			calendar_date: { required: true },
			final_price_pence: { required: true },
			property_id: { required: true },
			reservation_item_id: { required: true }
		}
	},
	'pricing.daily_price_grid': {
		fields: {
			base_price_pence: { required: true },
			calendar_date: { required: true },
			is_available: { required: true },
			max_los_restriction: { required: true },
			min_los_restriction: { required: true, min: 1 },
			property_id: { required: true },
			rate_plan_id: { required: true },
			room_type_id: { required: true }
		},
		comparisons: [
			{ field: 'max_los_restriction', operator: '>=', other: 'min_los_restriction' },
			{ field: 'max_los_restriction', operator: '>=', other: 'min_los_restriction' }
		]
	},
	'pricing.rate_plans': {
		fields: {
			code: { required: true, maxLength: 10 },
			currency_code: { required: true, exactLength: 3 },
			derivation_rule: {
				requiredWith: 'parent_rate_plan_id',
				jsonb: {
					type: { required: true, pattern: /percentage|fixed/ },
					value: { required: true }
				}
			},
			description: { maxLength: 300 },
			is_active: { required: true },
			name: { required: true, maxLength: 50 },
			parent_rate_plan_id: { requiredWith: 'derivation_rule' },
			property_id: { required: true }
		}
	},
	'pricing.seasonal_rates': {
		fields: {
			base_price_pence: { required: true },
			day_of_week: { required: true, min: 0 },
			min_los_restriction: { min: 1 },
			override_period: { required: true, validRange: true },
			property_id: { required: true },
			rate_plan_id: { required: true },
			room_type_id: { required: true }
		},
		comparisons: [
			{ field: 'max_los_restriction', operator: '>', other: 'min_los_restriction' },
			{ field: 'max_los_restriction', operator: '>', other: 'min_los_restriction' }
		],
		notes: [
			'GIST seasonal_rates_property_id_room_type_id_rate_plan_id_day_o_excl: EXCLUDE USING gist (property_id WITH \u003D, room_type_id WITH \u003D, rate_plan_id WITH \u003D, day_of_week WITH \u003D, override_period WITH \u0026\u0026) WHERE ((deleted_at IS NULL))'
		]
	},
	'public.goose_db_version': {
		fields: {
			is_applied: { required: true },
			tstamp: { required: true },
			version_id: { required: true }
		}
	},
	'relations.property_amenities': {
		fields: {
			amenity_id: { required: true },
			property_id: { required: true }
		}
	},
	'relations.reservation_item_guests': {
		fields: {
			guest_id: { required: true },
			property_id: { required: true },
			reservation_item_id: { required: true },
			role: { required: true }
		}
	},
	'relations.room_amenities': {
		fields: {
			amenity_id: { required: true },
			property_id: { required: true },
			room_id: { required: true }
		}
	},
	'relations.room_type_amenities': {
		fields: {
			amenity_id: { required: true },
			property_id: { required: true },
			room_type_id: { required: true }
		}
	},
	'sales_ledgers.accounts': {
		fields: {
			code: { required: true, maxLength: 10 },
			credit_limit_pence: { required: true, min: 0 },
			name: { required: true, maxLength: 100 },
			payment_terms_days: { required: true, min: 0 },
			property_id: { required: true }
		}
	},
	'sales_ledgers.transactions': {
		fields: {
			amount_pence: { required: true },
			due_date: { required: true },
			ledger_account_id: { required: true },
			posted_at: { required: true },
			property_id: { required: true },
			type: { required: true }
		}
	}
} as const;

export type ConstraintTable = keyof typeof CONSTRAINTS;
