// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: global.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getPropertyTimezone = `-- name: GetPropertyTimezone :one
SELECT timezone FROM operations.properties
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPropertyTimezone(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPropertyTimezone, id)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}

const notifyChannel = `-- name: NotifyChannel :exec
SELECT pg_notify($1::text, $2::text)
`

type NotifyChannelParams struct {
	Channel string `json:"channel"`
	Payload string `json:"payload"`
}

func (q *Queries) NotifyChannel(ctx context.Context, arg *NotifyChannelParams) error {
	_, err := q.db.Exec(ctx, notifyChannel, arg.Channel, arg.Payload)
	return err
}

const setCurrentPropertyID = `-- name: SetCurrentPropertyID :exec

SELECT set_config('app.current_property_id', $1::text, true)
`

// Cross-cutting queries used by ExecuteTx and notification infrastructure.
func (q *Queries) SetCurrentPropertyID(ctx context.Context, propertyID string) error {
	_, err := q.db.Exec(ctx, setCurrentPropertyID, propertyID)
	return err
}
