// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guest.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGuest = `-- name: CreateGuest :one

INSERT INTO identity.guests (
    property_id, first_name, last_name, email, phone_number
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, property_id, first_name, last_name, email, phone_number, preferences, notes, marketing_opt_in, is_anonymised, created_at, updated_at, deleted_at
`

type CreateGuestParams struct {
	PropertyID  uuid.UUID   `json:"property_id"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	Email       pgtype.Text `json:"email"`
	PhoneNumber pgtype.Text `json:"phone_number"`
}

// Guest queries for inline guest creation and expansion
func (q *Queries) CreateGuest(ctx context.Context, arg *CreateGuestParams) (IdentityGuest, error) {
	row := q.db.QueryRow(ctx, createGuest,
		arg.PropertyID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
	)
	var i IdentityGuest
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.Preferences,
		&i.Notes,
		&i.MarketingOptIn,
		&i.IsAnonymised,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGuest = `-- name: GetGuest :one
SELECT id, property_id, first_name, last_name, email, phone_number, preferences, notes, marketing_opt_in, is_anonymised, created_at, updated_at, deleted_at FROM identity.guests WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGuest(ctx context.Context, id uuid.UUID) (IdentityGuest, error) {
	row := q.db.QueryRow(ctx, getGuest, id)
	var i IdentityGuest
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.Preferences,
		&i.Notes,
		&i.MarketingOptIn,
		&i.IsAnonymised,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
