// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: property_settings.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getPropertySettings = `-- name: GetPropertySettings :one

SELECT website_hold_ttl_seconds, internal_hold_ttl_seconds
FROM operations.property_settings
WHERE property_id = $1
`

type GetPropertySettingsRow struct {
	WebsiteHoldTtlSeconds  int32 `json:"website_hold_ttl_seconds"`
	InternalHoldTtlSeconds int32 `json:"internal_hold_ttl_seconds"`
}

// Property settings lookup
func (q *Queries) GetPropertySettings(ctx context.Context, propertyID uuid.UUID) (GetPropertySettingsRow, error) {
	row := q.db.QueryRow(ctx, getPropertySettings, propertyID)
	var i GetPropertySettingsRow
	err := row.Scan(&i.WebsiteHoldTtlSeconds, &i.InternalHoldTtlSeconds)
	return i, err
}
