// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOutboxEvent(ctx context.Context, arg *CreateOutboxEventParams) (uuid.UUID, error)
	SetCurrentPropertyID(ctx context.Context, propertyID string) error
}

var _ Querier = (*Queries)(nil)
