// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	SetCurrentPropertyID(ctx context.Context, propertyID string) error
}

var _ Querier = (*Queries)(nil)
