// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApplyRateAdjustment(ctx context.Context, arg *ApplyRateAdjustmentParams) (pgconn.CommandTag, error)
	ApproveRateAdjustments(ctx context.Context, arg *ApproveRateAdjustmentsParams) error
	AvailabilityByType(ctx context.Context, arg *AvailabilityByTypeParams) ([]AvailabilityByTypeRow, error)
	BulkInsertBookedDailyRates(ctx context.Context, arg *BulkInsertBookedDailyRatesParams) error
	BulkInsertLedgerRows(ctx context.Context, arg *BulkInsertLedgerRowsParams) error
	// Used by both workers and service layer
	CancelReservationItems(ctx context.Context, arg *CancelReservationItemsParams) error
	// Check if a rate plan has capacity for the requested dates.
	//
	// 3-tier inheritance: daily_price_grid (most specific) > seasonal_rates > base_rates.
	// COALESCE tries each tier in order; first non-NULL wins. NULL = unlimited.
	// Only dates WITH a non-NULL capacity are checked against BDRs (fail early for unlimited).
	// Returns only dates where the limit is met or exceeded.
	//
	// See ADR-021 for the 3-tier capacity model.
	CheckRatePlanCapacity(ctx context.Context, arg *CheckRatePlanCapacityParams) ([]CheckRatePlanCapacityRow, error)
	// Returns conflicting dates for precise error messaging
	// @exclude_item_id is nullable: NULL = check all items
	ConflictCheckOnLedger(ctx context.Context, arg *ConflictCheckOnLedgerParams) ([]pgtype.Date, error)
	CreateOutboxEvent(ctx context.Context, arg *CreateOutboxEventParams) (uuid.UUID, error)
	// Reservation CRUD queries
	// See ADR-015 for state machine, ADR-020 for stay_period_envelope
	CreateReservation(ctx context.Context, arg *CreateReservationParams) (OperationsReservation, error)
	CreateReservationItem(ctx context.Context, arg *CreateReservationItemParams) (OperationsReservationItem, error)
	DeleteLedgerForReservation(ctx context.Context, arg *DeleteLedgerForReservationParams) error
	DeleteLedgerRowsByItem(ctx context.Context, arg *DeleteLedgerRowsByItemParams) error
	DeleteLedgerRowsByItemFromDate(ctx context.Context, arg *DeleteLedgerRowsByItemFromDateParams) error
	FindArchivableReservations(ctx context.Context) ([]OperationsReservation, error)
	// Reservation worker queries
	// Background sweeps for hold expiry, no-show reminders, overstays, archival
	FindExpiredHolds(ctx context.Context) ([]OperationsReservation, error)
	FindOverdueCheckins(ctx context.Context) ([]OperationsReservationItem, error)
	FindOverstays(ctx context.Context) ([]OperationsReservationItem, error)
	GetBookedRates(ctx context.Context, arg *GetBookedRatesParams) ([]PricingBookedDailyRate, error)
	GetReservation(ctx context.Context, id uuid.UUID) (GetReservationRow, error)
	// Reservation rate queries
	// All price changes go through adjustment column + audit log
	// Base price is immutable after creation
	// See ADR-021 for 3-tiered capacity model
	InsertBookedDailyRate(ctx context.Context, arg *InsertBookedDailyRateParams) error
	InsertLedgerRow(ctx context.Context, arg *InsertLedgerRowParams) error
	// Cursor pagination per ADR-014
	ListReservations(ctx context.Context, arg *ListReservationsParams) ([]OperationsReservation, error)
	// Reservation items queries
	// See ADR-015 for rollup rule, ADR-013 for locking & availability
	// ADR-015 rollup: item status changes drive reservation status
	// Returns new_status TEXT (NULL = unchanged)
	RollupReservationStatus(ctx context.Context, reservationID uuid.UUID) (string, error)
	// ADR-013: Auto-pin lowest available room of requested type
	SelectRoomForAutoPin(ctx context.Context, arg *SelectRoomForAutoPinParams) (uuid.UUID, error)
	SetCurrentPropertyID(ctx context.Context, propertyID string) error
	SoftDeleteBookedRatesNotInPeriod(ctx context.Context, arg *SoftDeleteBookedRatesNotInPeriodParams) error
	UpdateLedgerRowRoom(ctx context.Context, arg *UpdateLedgerRowRoomParams) error
	UpdateReservationItem(ctx context.Context, arg *UpdateReservationItemParams) (OperationsReservationItem, error)
	UpdateReservationMetadata(ctx context.Context, arg *UpdateReservationMetadataParams) (OperationsReservation, error)
	// Rollup applies the new status via service layer; version check prevents races
	UpdateReservationStatus(ctx context.Context, arg *UpdateReservationStatusParams) error
}

var _ Querier = (*Queries)(nil)
