// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation_workers.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const findArchivableReservations = `-- name: FindArchivableReservations :many
SELECT
  r.id, r.property_id, r.primary_guest_id, r.group_id, r.source, r.travel_agent_id, r.notes, r.status, r.version, r.created_at, r.updated_at, r.deleted_at, r.sequential, r.code, r.stay_period_envelope, r.expires_at, r.cancellation_intent
FROM
  operations.reservations r
JOIN operations.property_settings ps
  ON r.property_id = ps.property_id
WHERE
  r.status IN ('checked_out', 'cancelled')
  AND r.updated_at < NOW() - (ps.reservation_archive_after_days || ' days') ::INTERVAL
ORDER BY
  r.updated_at ASC
LIMIT 500 FOR UPDATE SKIP LOCKED
`

func (q *Queries) FindArchivableReservations(ctx context.Context) ([]OperationsReservation, error) {
	rows, err := q.db.Query(ctx, findArchivableReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsReservation
	for rows.Next() {
		var i OperationsReservation
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.PrimaryGuestID,
			&i.GroupID,
			&i.Source,
			&i.TravelAgentID,
			&i.Notes,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Sequential,
			&i.Code,
			&i.StayPeriodEnvelope,
			&i.ExpiresAt,
			&i.CancellationIntent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findExpiredHolds = `-- name: FindExpiredHolds :many

SELECT
  id, property_id, primary_guest_id, group_id, source, travel_agent_id, notes, status, version, created_at, updated_at, deleted_at, sequential, code, stay_period_envelope, expires_at, cancellation_intent
FROM
  operations.reservations
WHERE
  status = 'hold'
  AND expires_at < NOW()
ORDER BY
  created_at ASC
LIMIT 100 FOR UPDATE SKIP LOCKED
`

// Reservation worker queries
// Background sweeps for hold expiry, no-show reminders, overstays, archival
func (q *Queries) FindExpiredHolds(ctx context.Context) ([]OperationsReservation, error) {
	rows, err := q.db.Query(ctx, findExpiredHolds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsReservation
	for rows.Next() {
		var i OperationsReservation
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.PrimaryGuestID,
			&i.GroupID,
			&i.Source,
			&i.TravelAgentID,
			&i.Notes,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Sequential,
			&i.Code,
			&i.StayPeriodEnvelope,
			&i.ExpiresAt,
			&i.CancellationIntent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOverdueCheckins = `-- name: FindOverdueCheckins :many
SELECT
  ri.id, ri.property_id, ri.reservation_id, ri.booked_room_type_id, ri.assigned_room_id, ri.guest_id, ri.rate_plan_id, ri.stay_period, ri.base_rate_pence, ri.adults_count, ri.children_count, ri.status, ri.created_at, ri.updated_at, ri.deleted_at, ri.version, ri.do_not_move
FROM
  operations.reservation_items ri
JOIN operations.property_settings ps
  ON ri.property_id = ps.property_id
WHERE
  ri.status = 'booked'
  AND LOWER(ri.stay_period) + (ps.no_show_grace_minutes || ' minutes') ::INTERVAL < NOW()
`

func (q *Queries) FindOverdueCheckins(ctx context.Context) ([]OperationsReservationItem, error) {
	rows, err := q.db.Query(ctx, findOverdueCheckins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsReservationItem
	for rows.Next() {
		var i OperationsReservationItem
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.ReservationID,
			&i.BookedRoomTypeID,
			&i.AssignedRoomID,
			&i.GuestID,
			&i.RatePlanID,
			&i.StayPeriod,
			&i.BaseRatePence,
			&i.AdultsCount,
			&i.ChildrenCount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.DoNotMove,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOverstays = `-- name: FindOverstays :many
SELECT
  ri.id, ri.property_id, ri.reservation_id, ri.booked_room_type_id, ri.assigned_room_id, ri.guest_id, ri.rate_plan_id, ri.stay_period, ri.base_rate_pence, ri.adults_count, ri.children_count, ri.status, ri.created_at, ri.updated_at, ri.deleted_at, ri.version, ri.do_not_move
FROM
  operations.reservation_items ri
JOIN operations.property_settings ps
  ON ri.property_id = ps.property_id
WHERE
  ri.status = 'checked_in'
  AND NOW() > UPPER(ri.stay_period) + (ps.late_checkout_grace_minutes || ' minutes') ::INTERVAL
ORDER BY
  ri.updated_at ASC
LIMIT 100 FOR UPDATE SKIP LOCKED
`

func (q *Queries) FindOverstays(ctx context.Context) ([]OperationsReservationItem, error) {
	rows, err := q.db.Query(ctx, findOverstays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsReservationItem
	for rows.Next() {
		var i OperationsReservationItem
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.ReservationID,
			&i.BookedRoomTypeID,
			&i.AssignedRoomID,
			&i.GuestID,
			&i.RatePlanID,
			&i.StayPeriod,
			&i.BaseRatePence,
			&i.AdultsCount,
			&i.ChildrenCount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.DoNotMove,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservationStatus = `-- name: UpdateReservationStatus :exec
UPDATE operations.reservations
SET status = $1,
version = version + 1,
updated_at = NOW()
WHERE id = $2 AND version = $3
`

type UpdateReservationStatusParams struct {
	Status  OperationsReservationStatus `json:"status"`
	ID      uuid.UUID                   `json:"id"`
	Version int32                       `json:"version"`
}

// Rollup applies the new status via service layer; version check prevents races
func (q *Queries) UpdateReservationStatus(ctx context.Context, arg *UpdateReservationStatusParams) error {
	_, err := q.db.Exec(ctx, updateReservationStatus, arg.Status, arg.ID, arg.Version)
	return err
}
