// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation_rates.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRatePlanCapacity = `-- name: GetRatePlanCapacity :one
SELECT max_daily_capacity FROM pricing.base_rates 
WHERE rate_plan_id = $1 
  AND property_id = $2
  AND deleted_at IS NULL
`

type GetRatePlanCapacityParams struct {
	RatePlanID uuid.UUID `json:"rate_plan_id"`
	PropertyID uuid.UUID `json:"property_id"`
}

// Single-date capacity lookup (0 = unlimited).
func (q *Queries) GetRatePlanCapacity(ctx context.Context, arg *GetRatePlanCapacityParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getRatePlanCapacity, arg.RatePlanID, arg.PropertyID)
	var max_daily_capacity pgtype.Int4
	err := row.Scan(&max_daily_capacity)
	return max_daily_capacity, err
}
