// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation_finance.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createFolio = `-- name: CreateFolio :one

INSERT INTO finance.folios (
    property_id, reservation_id, folio_part, balance_pence
) VALUES (
    $1, $2, $3, 0
) RETURNING id, property_id, reservation_id, sales_ledger_id, folio_part, balance_pence, created_at, updated_at, deleted_at
`

type CreateFolioParams struct {
	PropertyID    uuid.UUID        `json:"property_id"`
	ReservationID uuid.NullUUID    `json:"reservation_id"`
	FolioPart     FinanceFolioPart `json:"folio_part"`
}

// Finance folio queries
func (q *Queries) CreateFolio(ctx context.Context, arg *CreateFolioParams) (FinanceFolio, error) {
	row := q.db.QueryRow(ctx, createFolio, arg.PropertyID, arg.ReservationID, arg.FolioPart)
	var i FinanceFolio
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.ReservationID,
		&i.SalesLedgerID,
		&i.FolioPart,
		&i.BalancePence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
