// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation_items.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const availabilityByType = `-- name: AvailabilityByType :many
SELECT 
    ril.calendar_date,
    COUNT(*) FILTER (WHERE ril.status = 'available')::INT AS available_count
FROM inventory.room_inventory_ledger ril
JOIN inventory.rooms r ON ril.room_id = r.id
WHERE r.property_id = $1
AND r.room_type_id = $2
AND ril.calendar_date BETWEEN $3::date AND $4::date
GROUP BY ril.calendar_date
ORDER BY ril.calendar_date
`

type AvailabilityByTypeParams struct {
	PropertyID uuid.UUID     `json:"property_id"`
	RoomTypeID uuid.NullUUID `json:"room_type_id"`
	StartDate  pgtype.Date   `json:"start_date"`
	EndDate    pgtype.Date   `json:"end_date"`
}

type AvailabilityByTypeRow struct {
	CalendarDate   pgtype.Date `json:"calendar_date"`
	AvailableCount int32       `json:"available_count"`
}

func (q *Queries) AvailabilityByType(ctx context.Context, arg *AvailabilityByTypeParams) ([]AvailabilityByTypeRow, error) {
	rows, err := q.db.Query(ctx, availabilityByType,
		arg.PropertyID,
		arg.RoomTypeID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailabilityByTypeRow
	for rows.Next() {
		var i AvailabilityByTypeRow
		if err := rows.Scan(&i.CalendarDate, &i.AvailableCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bulkInsertLedgerRows = `-- name: BulkInsertLedgerRows :exec
INSERT INTO inventory.room_inventory_ledger (
    property_id, room_id, reservation_id, reservation_item_id, calendar_date, status
) SELECT 
    unnest($1::uuid[]),
    unnest($2::uuid[]),
    unnest($3::uuid[]),
    unnest($4::uuid[]),
    unnest($5::date[]),
    unnest($6::inventory.inventory_status[])
`

type BulkInsertLedgerRowsParams struct {
	PropertyIds        []uuid.UUID                `json:"property_ids"`
	RoomIds            []uuid.UUID                `json:"room_ids"`
	ReservationIds     []uuid.UUID                `json:"reservation_ids"`
	ReservationItemIds []uuid.UUID                `json:"reservation_item_ids"`
	CalendarDates      []pgtype.Date              `json:"calendar_dates"`
	Statuses           []InventoryInventoryStatus `json:"statuses"`
}

func (q *Queries) BulkInsertLedgerRows(ctx context.Context, arg *BulkInsertLedgerRowsParams) error {
	_, err := q.db.Exec(ctx, bulkInsertLedgerRows,
		arg.PropertyIds,
		arg.RoomIds,
		arg.ReservationIds,
		arg.ReservationItemIds,
		arg.CalendarDates,
		arg.Statuses,
	)
	return err
}

const cancelReservationItems = `-- name: CancelReservationItems :exec
UPDATE operations.reservation_items
SET status = 'cancelled', deleted_at = NOW(), version = version + 1
WHERE reservation_id = $1
AND property_id = $2
AND status NOT IN ('checked_out', 'cancelled', 'archived')
AND version = $3
`

type CancelReservationItemsParams struct {
	ReservationID uuid.UUID `json:"reservation_id"`
	PropertyID    uuid.UUID `json:"property_id"`
	Version       int32     `json:"version"`
}

// Used by both workers and service layer
func (q *Queries) CancelReservationItems(ctx context.Context, arg *CancelReservationItemsParams) error {
	_, err := q.db.Exec(ctx, cancelReservationItems, arg.ReservationID, arg.PropertyID, arg.Version)
	return err
}

const conflictCheckOnLedger = `-- name: ConflictCheckOnLedger :many
SELECT ril.calendar_date::date
FROM inventory.room_inventory_ledger ril
WHERE ril.room_id = $1
AND ril.calendar_date = ANY($2::date[])
AND ril.property_id = $3
AND ril.status IN ('sold', 'on_hold', 'maintenance', 'decommissioned')
AND ril.deleted_at IS NULL
AND ($4::uuid IS NULL OR ril.reservation_item_id != $4)
ORDER BY ril.calendar_date
`

type ConflictCheckOnLedgerParams struct {
	RoomID        uuid.UUID     `json:"room_id"`
	Dates         []pgtype.Date `json:"dates"`
	PropertyID    uuid.UUID     `json:"property_id"`
	ExcludeItemID uuid.UUID     `json:"exclude_item_id"`
}

// Returns conflicting dates for precise error messaging
// @exclude_item_id is nullable: NULL = check all items
func (q *Queries) ConflictCheckOnLedger(ctx context.Context, arg *ConflictCheckOnLedgerParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, conflictCheckOnLedger,
		arg.RoomID,
		arg.Dates,
		arg.PropertyID,
		arg.ExcludeItemID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var ril_calendar_date pgtype.Date
		if err := rows.Scan(&ril_calendar_date); err != nil {
			return nil, err
		}
		items = append(items, ril_calendar_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteLedgerForReservation = `-- name: DeleteLedgerForReservation :exec
DELETE FROM inventory.room_inventory_ledger
WHERE reservation_id = $1
AND property_id = $2
`

type DeleteLedgerForReservationParams struct {
	ReservationID uuid.NullUUID `json:"reservation_id"`
	PropertyID    uuid.UUID     `json:"property_id"`
}

func (q *Queries) DeleteLedgerForReservation(ctx context.Context, arg *DeleteLedgerForReservationParams) error {
	_, err := q.db.Exec(ctx, deleteLedgerForReservation, arg.ReservationID, arg.PropertyID)
	return err
}

const deleteLedgerRowsByItem = `-- name: DeleteLedgerRowsByItem :exec
DELETE FROM inventory.room_inventory_ledger
WHERE reservation_item_id = $1
AND property_id = $2
`

type DeleteLedgerRowsByItemParams struct {
	ReservationItemID uuid.NullUUID `json:"reservation_item_id"`
	PropertyID        uuid.UUID     `json:"property_id"`
}

func (q *Queries) DeleteLedgerRowsByItem(ctx context.Context, arg *DeleteLedgerRowsByItemParams) error {
	_, err := q.db.Exec(ctx, deleteLedgerRowsByItem, arg.ReservationItemID, arg.PropertyID)
	return err
}

const deleteLedgerRowsByItemFromDate = `-- name: DeleteLedgerRowsByItemFromDate :exec
DELETE FROM inventory.room_inventory_ledger
WHERE reservation_item_id = $1
AND property_id = $2
AND calendar_date >= $3::date
`

type DeleteLedgerRowsByItemFromDateParams struct {
	ReservationItemID uuid.NullUUID `json:"reservation_item_id"`
	PropertyID        uuid.UUID     `json:"property_id"`
	FromDate          pgtype.Date   `json:"from_date"`
}

func (q *Queries) DeleteLedgerRowsByItemFromDate(ctx context.Context, arg *DeleteLedgerRowsByItemFromDateParams) error {
	_, err := q.db.Exec(ctx, deleteLedgerRowsByItemFromDate, arg.ReservationItemID, arg.PropertyID, arg.FromDate)
	return err
}

const insertLedgerRow = `-- name: InsertLedgerRow :exec
INSERT INTO inventory.room_inventory_ledger (
    property_id, room_id, reservation_id, reservation_item_id, calendar_date, status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type InsertLedgerRowParams struct {
	PropertyID        uuid.UUID                `json:"property_id"`
	RoomID            uuid.UUID                `json:"room_id"`
	ReservationID     uuid.NullUUID            `json:"reservation_id"`
	ReservationItemID uuid.NullUUID            `json:"reservation_item_id"`
	CalendarDate      pgtype.Date              `json:"calendar_date"`
	Status            InventoryInventoryStatus `json:"status"`
}

func (q *Queries) InsertLedgerRow(ctx context.Context, arg *InsertLedgerRowParams) error {
	_, err := q.db.Exec(ctx, insertLedgerRow,
		arg.PropertyID,
		arg.RoomID,
		arg.ReservationID,
		arg.ReservationItemID,
		arg.CalendarDate,
		arg.Status,
	)
	return err
}

const rollupReservationStatus = `-- name: RollupReservationStatus :one

SELECT 
    CASE 
        WHEN COUNT(*) = 0 THEN 'cancelled'::operations.reservation_status
        WHEN COUNT(*) FILTER (WHERE status IN ('checked_out', 'no_show', 'cancelled', 'archived')) = COUNT(*) AND COUNT(*) FILTER (WHERE status = 'checked_out') > 0 THEN 'checked_out'::operations.reservation_status
        WHEN COUNT(*) FILTER (WHERE status = 'checked_in') > 0 AND COUNT(*) FILTER (WHERE status = 'booked') = 0 THEN 'checked_in'::operations.reservation_status
        ELSE NULL
    END::TEXT AS new_status
FROM operations.reservation_items
WHERE reservation_id = $1 AND deleted_at IS NULL
`

// Reservation items queries
// See ADR-015 for rollup rule, ADR-013 for locking & availability
// ADR-015 rollup: item status changes drive reservation status
// Returns new_status TEXT (NULL = unchanged)
func (q *Queries) RollupReservationStatus(ctx context.Context, reservationID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, rollupReservationStatus, reservationID)
	var new_status string
	err := row.Scan(&new_status)
	return new_status, err
}

const selectRoomForAutoPin = `-- name: SelectRoomForAutoPin :one
SELECT r.id FROM inventory.rooms r
LEFT JOIN inventory.room_inventory_ledger ril ON r.id = ril.room_id 
    AND ril.calendar_date = ANY($1::date[])
    AND ril.status IN ('sold', 'on_hold', 'maintenance', 'decommissioned')
    AND ril.deleted_at IS NULL
WHERE r.property_id = $2
AND r.room_type_id = $3
AND ril.id IS NULL
ORDER BY r.name ASC
LIMIT 1 FOR UPDATE SKIP LOCKED
`

type SelectRoomForAutoPinParams struct {
	Dates      []pgtype.Date `json:"dates"`
	PropertyID uuid.UUID     `json:"property_id"`
	RoomTypeID uuid.NullUUID `json:"room_type_id"`
}

// ADR-013: Auto-pin lowest available room of requested type
func (q *Queries) SelectRoomForAutoPin(ctx context.Context, arg *SelectRoomForAutoPinParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, selectRoomForAutoPin, arg.Dates, arg.PropertyID, arg.RoomTypeID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateLedgerRowRoom = `-- name: UpdateLedgerRowRoom :exec
UPDATE inventory.room_inventory_ledger
SET room_id = $1
WHERE reservation_item_id = $2
AND property_id = $3
`

type UpdateLedgerRowRoomParams struct {
	NewRoomID         uuid.UUID     `json:"new_room_id"`
	ReservationItemID uuid.NullUUID `json:"reservation_item_id"`
	PropertyID        uuid.UUID     `json:"property_id"`
}

func (q *Queries) UpdateLedgerRowRoom(ctx context.Context, arg *UpdateLedgerRowRoomParams) error {
	_, err := q.db.Exec(ctx, updateLedgerRowRoom, arg.NewRoomID, arg.ReservationItemID, arg.PropertyID)
	return err
}
