// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation_workers.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const findArchivableReservations = `-- name: FindArchivableReservations :many
SELECT
  id, property_id, primary_guest_id, sequential, code, source, notes, status, stay_period_envelope, version, created_at, updated_at, deleted_at, expires_at
FROM
  operations.reservations
WHERE
  status IN ('checked_out', 'cancelled')
  AND updated_at < NOW() - (365 || ' days') ::INTERVAL
ORDER BY
  updated_at ASC
LIMIT 500 FOR UPDATE SKIP LOCKED
`

func (q *Queries) FindArchivableReservations(ctx context.Context) ([]OperationsReservation, error) {
	rows, err := q.db.Query(ctx, findArchivableReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsReservation
	for rows.Next() {
		var i OperationsReservation
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.PrimaryGuestID,
			&i.Sequential,
			&i.Code,
			&i.Source,
			&i.Notes,
			&i.Status,
			&i.StayPeriodEnvelope,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findExpiredHolds = `-- name: FindExpiredHolds :many

SELECT
  id, property_id, primary_guest_id, sequential, code, source, notes, status, stay_period_envelope, version, created_at, updated_at, deleted_at, expires_at
FROM
  operations.reservations
WHERE
  status = 'hold'
  AND expires_at < NOW()
ORDER BY
  created_at ASC
LIMIT 100 FOR UPDATE SKIP LOCKED
`

// Reservation worker queries
// Background sweeps for hold expiry, no-show reminders, overstays, archival
func (q *Queries) FindExpiredHolds(ctx context.Context) ([]OperationsReservation, error) {
	rows, err := q.db.Query(ctx, findExpiredHolds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsReservation
	for rows.Next() {
		var i OperationsReservation
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.PrimaryGuestID,
			&i.Sequential,
			&i.Code,
			&i.Source,
			&i.Notes,
			&i.Status,
			&i.StayPeriodEnvelope,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOverdueCheckins = `-- name: FindOverdueCheckins :many
SELECT
  id, property_id, reservation_id, booked_room_type_id, assigned_room_id, guest_id, rate_plan_id, stay_period, do_not_move, base_rate_pence, adults_count, children_count, status, version, created_at, updated_at, deleted_at
FROM
  operations.reservation_items
WHERE
  status = 'booked'
  AND LOWER(stay_period) + (100 || ' minutes') ::INTERVAL < NOW()
`

func (q *Queries) FindOverdueCheckins(ctx context.Context) ([]OperationsReservationItem, error) {
	rows, err := q.db.Query(ctx, findOverdueCheckins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsReservationItem
	for rows.Next() {
		var i OperationsReservationItem
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.ReservationID,
			&i.BookedRoomTypeID,
			&i.AssignedRoomID,
			&i.GuestID,
			&i.RatePlanID,
			&i.StayPeriod,
			&i.DoNotMove,
			&i.BaseRatePence,
			&i.AdultsCount,
			&i.ChildrenCount,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOverstays = `-- name: FindOverstays :many
SELECT
  id, property_id, reservation_id, booked_room_type_id, assigned_room_id, guest_id, rate_plan_id, stay_period, do_not_move, base_rate_pence, adults_count, children_count, status, version, created_at, updated_at, deleted_at
FROM
  operations.reservation_items
WHERE
  status = 'checked_in'
  AND NOW() > UPPER(stay_period) + (100 || ' minutes') ::INTERVAL
ORDER BY
  updated_at ASC
LIMIT 100 FOR UPDATE SKIP LOCKED
`

func (q *Queries) FindOverstays(ctx context.Context) ([]OperationsReservationItem, error) {
	rows, err := q.db.Query(ctx, findOverstays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsReservationItem
	for rows.Next() {
		var i OperationsReservationItem
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.ReservationID,
			&i.BookedRoomTypeID,
			&i.AssignedRoomID,
			&i.GuestID,
			&i.RatePlanID,
			&i.StayPeriod,
			&i.DoNotMove,
			&i.BaseRatePence,
			&i.AdultsCount,
			&i.ChildrenCount,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservationStatus = `-- name: UpdateReservationStatus :execrows
UPDATE operations.reservations
SET status = $1,
  version = version + 1,
  updated_at = NOW()
WHERE id = $2 AND version = $3
`

type UpdateReservationStatusParams struct {
	Status  OperationsReservationStatus `json:"status"`
	ID      uuid.UUID                   `json:"id"`
	Version int32                       `json:"version"`
}

// Rollup applies the new status via service layer; version check prevents races
func (q *Queries) UpdateReservationStatus(ctx context.Context, arg *UpdateReservationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReservationStatus, arg.Status, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
