// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation_rates.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBaseRate = `-- name: GetBaseRate :one
SELECT base_price_pence FROM pricing.base_rates
WHERE property_id = $1
  AND room_type_id = $2
  AND rate_plan_id = $3
  AND day_of_week = $4
  AND deleted_at IS NULL
`

type GetBaseRateParams struct {
	PropertyID uuid.UUID `json:"property_id"`
	RoomTypeID uuid.UUID `json:"room_type_id"`
	RatePlanID uuid.UUID `json:"rate_plan_id"`
	DayOfWeek  int32     `json:"day_of_week"`
}

// Lookup base nightly rate by day-of-week. No date overrides resolved.
func (q *Queries) GetBaseRate(ctx context.Context, arg *GetBaseRateParams) (int32, error) {
	row := q.db.QueryRow(ctx, getBaseRate,
		arg.PropertyID,
		arg.RoomTypeID,
		arg.RatePlanID,
		arg.DayOfWeek,
	)
	var base_price_pence int32
	err := row.Scan(&base_price_pence)
	return base_price_pence, err
}

const getRatePlanCapacity = `-- name: GetRatePlanCapacity :one
SELECT max_daily_capacity FROM pricing.base_rates 
WHERE rate_plan_id = $1 
  AND property_id = $2
  AND deleted_at IS NULL
`

type GetRatePlanCapacityParams struct {
	RatePlanID uuid.UUID `json:"rate_plan_id"`
	PropertyID uuid.UUID `json:"property_id"`
}

// Single-date capacity lookup (0 = unlimited).
func (q *Queries) GetRatePlanCapacity(ctx context.Context, arg *GetRatePlanCapacityParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getRatePlanCapacity, arg.RatePlanID, arg.PropertyID)
	var max_daily_capacity pgtype.Int4
	err := row.Scan(&max_daily_capacity)
	return max_daily_capacity, err
}
