// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation_rates.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyRateAdjustment = `-- name: ApplyRateAdjustment :execresult
UPDATE pricing.booked_daily_rates
SET adjustment = jsonb_build_object('type', $1, 'value', $2, 'reason', $3)
WHERE reservation_item_id = $4
AND property_id = $5
AND calendar_date = $6
RETURNING id, property_id, reservation_item_id, calendar_date, rate_plan_id, base_price_pence, adjustment, adjustment_approved, adjustment_approved_by_user_id, final_price_pence, created_at, updated_at, deleted_at
`

type ApplyRateAdjustmentParams struct {
	Type              interface{} `json:"type"`
	Value             interface{} `json:"value"`
	Reason            interface{} `json:"reason"`
	ReservationItemID uuid.UUID   `json:"reservation_item_id"`
	PropertyID        uuid.UUID   `json:"property_id"`
	CalendarDate      pgtype.Date `json:"calendar_date"`
}

func (q *Queries) ApplyRateAdjustment(ctx context.Context, arg *ApplyRateAdjustmentParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, applyRateAdjustment,
		arg.Type,
		arg.Value,
		arg.Reason,
		arg.ReservationItemID,
		arg.PropertyID,
		arg.CalendarDate,
	)
}

const approveRateAdjustments = `-- name: ApproveRateAdjustments :exec
UPDATE pricing.booked_daily_rates
SET adjustment_approved = true, adjustment_approved_by_user_id = $1
WHERE reservation_item_id = $2
AND property_id = $3
AND calendar_date = ANY($4::date[])
`

type ApproveRateAdjustmentsParams struct {
	UserID            uuid.NullUUID `json:"user_id"`
	ReservationItemID uuid.UUID     `json:"reservation_item_id"`
	PropertyID        uuid.UUID     `json:"property_id"`
	Dates             []pgtype.Date `json:"dates"`
}

func (q *Queries) ApproveRateAdjustments(ctx context.Context, arg *ApproveRateAdjustmentsParams) error {
	_, err := q.db.Exec(ctx, approveRateAdjustments,
		arg.UserID,
		arg.ReservationItemID,
		arg.PropertyID,
		arg.Dates,
	)
	return err
}

const bulkInsertBookedDailyRates = `-- name: BulkInsertBookedDailyRates :exec
INSERT INTO pricing.booked_daily_rates (
    property_id, reservation_item_id, calendar_date, rate_plan_id, base_price_pence
) SELECT 
    unnest($1::uuid[]),
    unnest($2::uuid[]),
    unnest($3::date[]),
    unnest($4::uuid[])::uuid,
    unnest($5::int[])
`

type BulkInsertBookedDailyRatesParams struct {
	PropertyIds        []uuid.UUID   `json:"property_ids"`
	ReservationItemIds []uuid.UUID   `json:"reservation_item_ids"`
	CalendarDates      []pgtype.Date `json:"calendar_dates"`
	RatePlanIds        []uuid.UUID   `json:"rate_plan_ids"`
	BasePricePences    []int32       `json:"base_price_pences"`
}

func (q *Queries) BulkInsertBookedDailyRates(ctx context.Context, arg *BulkInsertBookedDailyRatesParams) error {
	_, err := q.db.Exec(ctx, bulkInsertBookedDailyRates,
		arg.PropertyIds,
		arg.ReservationItemIds,
		arg.CalendarDates,
		arg.RatePlanIds,
		arg.BasePricePences,
	)
	return err
}

const checkRatePlanCapacity = `-- name: CheckRatePlanCapacity :many
WITH limited_dates AS (
    SELECT d.calendar_date,
           COALESCE(
               (SELECT dp.daily_room_capacity FROM pricing.daily_price_grid dp 
                WHERE dp.rate_plan_id = $1 AND dp.calendar_date = d.calendar_date AND dp.property_id = $2),
               (SELECT sr.max_daily_capacity FROM pricing.seasonal_rates sr 
                WHERE sr.rate_plan_id = $1 AND d.calendar_date <@ sr.override_period AND sr.property_id = $2
                LIMIT 1),
               (SELECT br.max_daily_capacity FROM pricing.base_rates br 
                WHERE br.rate_plan_id = $1 AND br.property_id = $2
                LIMIT 1)
           ) AS daily_room_capacity
    FROM unnest($3::date[]) AS d(calendar_date)
)
SELECT ld.calendar_date, 
       COUNT(bdr.id)::INT AS current_bookings,
       ld.daily_room_capacity
FROM limited_dates ld
LEFT JOIN pricing.booked_daily_rates bdr ON bdr.rate_plan_id = $1
    AND bdr.calendar_date = ld.calendar_date
    AND bdr.property_id = $2
    AND bdr.deleted_at IS NULL
WHERE ld.daily_room_capacity IS NOT NULL
GROUP BY ld.calendar_date, ld.daily_room_capacity
HAVING COUNT(bdr.id) >= ld.daily_room_capacity
`

type CheckRatePlanCapacityParams struct {
	RatePlanID uuid.NullUUID `json:"rate_plan_id"`
	PropertyID uuid.UUID     `json:"property_id"`
	Dates      []pgtype.Date `json:"dates"`
}

type CheckRatePlanCapacityRow struct {
	CalendarDate      interface{} `json:"calendar_date"`
	CurrentBookings   int32       `json:"current_bookings"`
	DailyRoomCapacity interface{} `json:"daily_room_capacity"`
}

// Check if a rate plan has capacity for the requested dates.
//
// 3-tier inheritance: daily_price_grid (most specific) > seasonal_rates > base_rates.
// COALESCE tries each tier in order; first non-NULL wins. NULL = unlimited.
// Only dates WITH a non-NULL capacity are checked against BDRs (fail early for unlimited).
// Returns only dates where the limit is met or exceeded.
//
// See ADR-021 for the 3-tier capacity model.
func (q *Queries) CheckRatePlanCapacity(ctx context.Context, arg *CheckRatePlanCapacityParams) ([]CheckRatePlanCapacityRow, error) {
	rows, err := q.db.Query(ctx, checkRatePlanCapacity, arg.RatePlanID, arg.PropertyID, arg.Dates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckRatePlanCapacityRow
	for rows.Next() {
		var i CheckRatePlanCapacityRow
		if err := rows.Scan(&i.CalendarDate, &i.CurrentBookings, &i.DailyRoomCapacity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookedRates = `-- name: GetBookedRates :many
SELECT id, property_id, reservation_item_id, calendar_date, rate_plan_id, base_price_pence, adjustment, adjustment_approved, adjustment_approved_by_user_id, final_price_pence, created_at, updated_at, deleted_at FROM pricing.booked_daily_rates
WHERE reservation_item_id = $1
AND property_id = $2
AND deleted_at IS NULL
ORDER BY calendar_date
`

type GetBookedRatesParams struct {
	ReservationItemID uuid.UUID `json:"reservation_item_id"`
	PropertyID        uuid.UUID `json:"property_id"`
}

func (q *Queries) GetBookedRates(ctx context.Context, arg *GetBookedRatesParams) ([]PricingBookedDailyRate, error) {
	rows, err := q.db.Query(ctx, getBookedRates, arg.ReservationItemID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PricingBookedDailyRate
	for rows.Next() {
		var i PricingBookedDailyRate
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.ReservationItemID,
			&i.CalendarDate,
			&i.RatePlanID,
			&i.BasePricePence,
			&i.Adjustment,
			&i.AdjustmentApproved,
			&i.AdjustmentApprovedByUserID,
			&i.FinalPricePence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBookedDailyRate = `-- name: InsertBookedDailyRate :exec

INSERT INTO pricing.booked_daily_rates (
    property_id, reservation_item_id, calendar_date, rate_plan_id, base_price_pence
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertBookedDailyRateParams struct {
	PropertyID        uuid.UUID     `json:"property_id"`
	ReservationItemID uuid.UUID     `json:"reservation_item_id"`
	CalendarDate      pgtype.Date   `json:"calendar_date"`
	RatePlanID        uuid.NullUUID `json:"rate_plan_id"`
	BasePricePence    int32         `json:"base_price_pence"`
}

// Reservation rate queries
// All price changes go through adjustment column + audit log
// Base price is immutable after creation
// See ADR-021 for 3-tiered capacity model
func (q *Queries) InsertBookedDailyRate(ctx context.Context, arg *InsertBookedDailyRateParams) error {
	_, err := q.db.Exec(ctx, insertBookedDailyRate,
		arg.PropertyID,
		arg.ReservationItemID,
		arg.CalendarDate,
		arg.RatePlanID,
		arg.BasePricePence,
	)
	return err
}

const softDeleteBookedRatesNotInPeriod = `-- name: SoftDeleteBookedRatesNotInPeriod :exec
UPDATE pricing.booked_daily_rates
SET deleted_at = NOW()
WHERE reservation_item_id = $1
AND property_id = $2
AND deleted_at IS NULL
AND calendar_date NOT IN (SELECT unnest($3::date[]))
`

type SoftDeleteBookedRatesNotInPeriodParams struct {
	ReservationItemID uuid.UUID     `json:"reservation_item_id"`
	PropertyID        uuid.UUID     `json:"property_id"`
	Dates             []pgtype.Date `json:"dates"`
}

func (q *Queries) SoftDeleteBookedRatesNotInPeriod(ctx context.Context, arg *SoftDeleteBookedRatesNotInPeriodParams) error {
	_, err := q.db.Exec(ctx, softDeleteBookedRatesNotInPeriod, arg.ReservationItemID, arg.PropertyID, arg.Dates)
	return err
}
