// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation_crud.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReservation = `-- name: CreateReservation :one

INSERT INTO operations.reservations (
    property_id, primary_guest_id, group_id, source, travel_agent_id, notes, status, version, stay_period_envelope, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 1, $8, $9
) RETURNING id, property_id, primary_guest_id, group_id, source, travel_agent_id, notes, status, version, created_at, updated_at, deleted_at, sequential, code, stay_period_envelope, expires_at, cancellation_intent
`

type CreateReservationParams struct {
	PropertyID         uuid.UUID                        `json:"property_id"`
	PrimaryGuestID     uuid.UUID                        `json:"primary_guest_id"`
	GroupID            uuid.NullUUID                    `json:"group_id"`
	Source             OperationsReservationSource      `json:"source"`
	TravelAgentID      uuid.NullUUID                    `json:"travel_agent_id"`
	Notes              pgtype.Text                      `json:"notes"`
	Status             OperationsReservationStatus      `json:"status"`
	StayPeriodEnvelope pgtype.Range[pgtype.Timestamptz] `json:"stay_period_envelope"`
	ExpiresAt          pgtype.Timestamptz               `json:"expires_at"`
}

// Reservation CRUD queries
// See ADR-015 for state machine, ADR-020 for stay_period_envelope
func (q *Queries) CreateReservation(ctx context.Context, arg *CreateReservationParams) (OperationsReservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.PropertyID,
		arg.PrimaryGuestID,
		arg.GroupID,
		arg.Source,
		arg.TravelAgentID,
		arg.Notes,
		arg.Status,
		arg.StayPeriodEnvelope,
		arg.ExpiresAt,
	)
	var i OperationsReservation
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.PrimaryGuestID,
		&i.GroupID,
		&i.Source,
		&i.TravelAgentID,
		&i.Notes,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Sequential,
		&i.Code,
		&i.StayPeriodEnvelope,
		&i.ExpiresAt,
		&i.CancellationIntent,
	)
	return i, err
}

const createReservationItem = `-- name: CreateReservationItem :one
INSERT INTO operations.reservation_items (
    property_id, reservation_id, booked_room_type_id, assigned_room_id, guest_id, rate_plan_id, stay_period, base_rate_pence, adults_count, children_count, status, version, do_not_move
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 1, $12
) RETURNING id, property_id, reservation_id, booked_room_type_id, assigned_room_id, guest_id, rate_plan_id, stay_period, base_rate_pence, adults_count, children_count, status, created_at, updated_at, deleted_at, version, do_not_move
`

type CreateReservationItemParams struct {
	PropertyID       uuid.UUID                        `json:"property_id"`
	ReservationID    uuid.UUID                        `json:"reservation_id"`
	BookedRoomTypeID uuid.UUID                        `json:"booked_room_type_id"`
	AssignedRoomID   uuid.NullUUID                    `json:"assigned_room_id"`
	GuestID          uuid.NullUUID                    `json:"guest_id"`
	RatePlanID       uuid.NullUUID                    `json:"rate_plan_id"`
	StayPeriod       pgtype.Range[pgtype.Timestamptz] `json:"stay_period"`
	BaseRatePence    int32                            `json:"base_rate_pence"`
	AdultsCount      int32                            `json:"adults_count"`
	ChildrenCount    int32                            `json:"children_count"`
	Status           OperationsReservationItemStatus  `json:"status"`
	DoNotMove        bool                             `json:"do_not_move"`
}

func (q *Queries) CreateReservationItem(ctx context.Context, arg *CreateReservationItemParams) (OperationsReservationItem, error) {
	row := q.db.QueryRow(ctx, createReservationItem,
		arg.PropertyID,
		arg.ReservationID,
		arg.BookedRoomTypeID,
		arg.AssignedRoomID,
		arg.GuestID,
		arg.RatePlanID,
		arg.StayPeriod,
		arg.BaseRatePence,
		arg.AdultsCount,
		arg.ChildrenCount,
		arg.Status,
		arg.DoNotMove,
	)
	var i OperationsReservationItem
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.ReservationID,
		&i.BookedRoomTypeID,
		&i.AssignedRoomID,
		&i.GuestID,
		&i.RatePlanID,
		&i.StayPeriod,
		&i.BaseRatePence,
		&i.AdultsCount,
		&i.ChildrenCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.DoNotMove,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT 
    r.id, r.property_id, r.primary_guest_id, r.group_id, r.source, r.travel_agent_id, r.notes, r.status, r.version, r.created_at, r.updated_at, r.deleted_at, r.sequential, r.code, r.stay_period_envelope, r.expires_at, r.cancellation_intent,
    COALESCE(
        json_agg(
            json_build_object(
                'id', i.id,
                'property_id', i.property_id,
                'reservation_id', i.reservation_id,
                'booked_room_type_id', i.booked_room_type_id,
                'assigned_room_id', i.assigned_room_id,
                'guest_id', i.guest_id,
                'rate_plan_id', i.rate_plan_id,
                'stay_period', i.stay_period,
                'base_rate_pence', i.base_rate_pence,
                'adults_count', i.adults_count,
                'children_count', i.children_count,
                'status', i.status,
                'version', i.version,
                'do_not_move', i.do_not_move,
                'created_at', i.created_at,
                'updated_at', i.updated_at,
                'deleted_at', i.deleted_at
            )
        ) FILTER (WHERE i.id IS NOT NULL), '[]'::json
    ) AS items
FROM operations.reservations r
LEFT JOIN operations.reservation_items i ON r.id = i.reservation_id AND i.deleted_at IS NULL
WHERE r.id = $1 AND r.deleted_at IS NULL
GROUP BY r.id
`

type GetReservationRow struct {
	ID                 uuid.UUID                        `json:"id"`
	PropertyID         uuid.UUID                        `json:"property_id"`
	PrimaryGuestID     uuid.UUID                        `json:"primary_guest_id"`
	GroupID            uuid.NullUUID                    `json:"group_id"`
	Source             OperationsReservationSource      `json:"source"`
	TravelAgentID      uuid.NullUUID                    `json:"travel_agent_id"`
	Notes              pgtype.Text                      `json:"notes"`
	Status             OperationsReservationStatus      `json:"status"`
	Version            int32                            `json:"version"`
	CreatedAt          pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz               `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz               `json:"deleted_at"`
	Sequential         int64                            `json:"sequential"`
	Code               string                           `json:"code"`
	StayPeriodEnvelope pgtype.Range[pgtype.Timestamptz] `json:"stay_period_envelope"`
	ExpiresAt          pgtype.Timestamptz               `json:"expires_at"`
	CancellationIntent []byte                           `json:"cancellation_intent"`
	Items              interface{}                      `json:"items"`
}

func (q *Queries) GetReservation(ctx context.Context, id uuid.UUID) (GetReservationRow, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i GetReservationRow
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.PrimaryGuestID,
		&i.GroupID,
		&i.Source,
		&i.TravelAgentID,
		&i.Notes,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Sequential,
		&i.Code,
		&i.StayPeriodEnvelope,
		&i.ExpiresAt,
		&i.CancellationIntent,
		&i.Items,
	)
	return i, err
}

const listReservations = `-- name: ListReservations :many
SELECT r.id, r.property_id, r.primary_guest_id, r.group_id, r.source, r.travel_agent_id, r.notes, r.status, r.version, r.created_at, r.updated_at, r.deleted_at, r.sequential, r.code, r.stay_period_envelope, r.expires_at, r.cancellation_intent 
FROM operations.reservations r
WHERE r.property_id = $1 
AND r.deleted_at IS NULL
AND ($2::text = '' OR r.status::text = $2::text)
AND ($3::timestamptz IS NULL OR lower(r.stay_period_envelope) < $3
    OR (lower(r.stay_period_envelope) = $3 AND r.id < $4))
AND ($5::date IS NULL OR lower(r.stay_period_envelope) >= $5::date)
AND ($6::date IS NULL OR upper(r.stay_period_envelope) <= $6::date)
ORDER BY lower(r.stay_period_envelope) DESC, r.id DESC
LIMIT $7
`

type ListReservationsParams struct {
	PropertyID uuid.UUID          `json:"property_id"`
	Status     string             `json:"status"`
	CursorDate pgtype.Timestamptz `json:"cursor_date"`
	CursorID   uuid.UUID          `json:"cursor_id"`
	StartDate  pgtype.Date        `json:"start_date"`
	EndDate    pgtype.Date        `json:"end_date"`
	Limit      int32              `json:"limit"`
}

// Cursor pagination per ADR-014
func (q *Queries) ListReservations(ctx context.Context, arg *ListReservationsParams) ([]OperationsReservation, error) {
	rows, err := q.db.Query(ctx, listReservations,
		arg.PropertyID,
		arg.Status,
		arg.CursorDate,
		arg.CursorID,
		arg.StartDate,
		arg.EndDate,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsReservation
	for rows.Next() {
		var i OperationsReservation
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.PrimaryGuestID,
			&i.GroupID,
			&i.Source,
			&i.TravelAgentID,
			&i.Notes,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Sequential,
			&i.Code,
			&i.StayPeriodEnvelope,
			&i.ExpiresAt,
			&i.CancellationIntent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservationItem = `-- name: UpdateReservationItem :one
UPDATE operations.reservation_items 
SET 
    booked_room_type_id = COALESCE($1, booked_room_type_id),
    assigned_room_id = COALESCE($2, assigned_room_id),
    stay_period = COALESCE($3, stay_period),
    rate_plan_id = COALESCE($4, rate_plan_id),
    adults_count = COALESCE($5, adults_count),
    children_count = COALESCE($6, children_count),
    status = COALESCE($7, status),
    version = version + 1,
    updated_at = NOW()
WHERE id = $8 AND version = $9
RETURNING id, property_id, reservation_id, booked_room_type_id, assigned_room_id, guest_id, rate_plan_id, stay_period, base_rate_pence, adults_count, children_count, status, created_at, updated_at, deleted_at, version, do_not_move
`

type UpdateReservationItemParams struct {
	BookedRoomTypeID uuid.NullUUID                    `json:"booked_room_type_id"`
	AssignedRoomID   uuid.NullUUID                    `json:"assigned_room_id"`
	StayPeriod       pgtype.Range[pgtype.Timestamptz] `json:"stay_period"`
	RatePlanID       uuid.NullUUID                    `json:"rate_plan_id"`
	AdultsCount      int32                            `json:"adults_count"`
	ChildrenCount    int32                            `json:"children_count"`
	Status           OperationsReservationItemStatus  `json:"status"`
	ID               uuid.UUID                        `json:"id"`
	Version          int32                            `json:"version"`
}

func (q *Queries) UpdateReservationItem(ctx context.Context, arg *UpdateReservationItemParams) (OperationsReservationItem, error) {
	row := q.db.QueryRow(ctx, updateReservationItem,
		arg.BookedRoomTypeID,
		arg.AssignedRoomID,
		arg.StayPeriod,
		arg.RatePlanID,
		arg.AdultsCount,
		arg.ChildrenCount,
		arg.Status,
		arg.ID,
		arg.Version,
	)
	var i OperationsReservationItem
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.ReservationID,
		&i.BookedRoomTypeID,
		&i.AssignedRoomID,
		&i.GuestID,
		&i.RatePlanID,
		&i.StayPeriod,
		&i.BaseRatePence,
		&i.AdultsCount,
		&i.ChildrenCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.DoNotMove,
	)
	return i, err
}

const updateReservationMetadata = `-- name: UpdateReservationMetadata :one
UPDATE operations.reservations 
SET 
    notes = COALESCE($1, notes),
    travel_agent_id = COALESCE($2, travel_agent_id),
    group_id = COALESCE($3, group_id),
    primary_guest_id = COALESCE($4, primary_guest_id),
    stay_period_envelope = COALESCE($5, stay_period_envelope),
    version = version + 1,
    updated_at = NOW()
WHERE id = $6 AND version = $7
RETURNING id, property_id, primary_guest_id, group_id, source, travel_agent_id, notes, status, version, created_at, updated_at, deleted_at, sequential, code, stay_period_envelope, expires_at, cancellation_intent
`

type UpdateReservationMetadataParams struct {
	Notes              pgtype.Text                      `json:"notes"`
	TravelAgentID      uuid.NullUUID                    `json:"travel_agent_id"`
	GroupID            uuid.NullUUID                    `json:"group_id"`
	PrimaryGuestID     uuid.UUID                        `json:"primary_guest_id"`
	StayPeriodEnvelope pgtype.Range[pgtype.Timestamptz] `json:"stay_period_envelope"`
	ID                 uuid.UUID                        `json:"id"`
	Version            int32                            `json:"version"`
}

func (q *Queries) UpdateReservationMetadata(ctx context.Context, arg *UpdateReservationMetadataParams) (OperationsReservation, error) {
	row := q.db.QueryRow(ctx, updateReservationMetadata,
		arg.Notes,
		arg.TravelAgentID,
		arg.GroupID,
		arg.PrimaryGuestID,
		arg.StayPeriodEnvelope,
		arg.ID,
		arg.Version,
	)
	var i OperationsReservation
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.PrimaryGuestID,
		&i.GroupID,
		&i.Source,
		&i.TravelAgentID,
		&i.Notes,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Sequential,
		&i.Code,
		&i.StayPeriodEnvelope,
		&i.ExpiresAt,
		&i.CancellationIntent,
	)
	return i, err
}
