// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tape_chart.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTapeChartInventory = `-- name: GetTapeChartInventory :many
SELECT
    l.id,
    l.property_id,
    l.room_id,
    l.reservation_id,
    l.reservation_item_id,
    l.maintenance_block_id,
    l.calendar_date,
    l.status,
    r.name AS room_name,
    l.room_type_id
FROM inventory.room_inventory_ledger l
JOIN inventory.rooms r ON r.id = l.room_id
WHERE l.property_id = $1
  AND l.calendar_date >= $2::date
  AND l.calendar_date < $3::date
  AND l.deleted_at IS NULL
ORDER BY l.calendar_date, l.room_id
`

type GetTapeChartInventoryParams struct {
	PropertyID uuid.UUID   `json:"property_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
}

type GetTapeChartInventoryRow struct {
	ID                 uuid.UUID                `json:"id"`
	PropertyID         uuid.UUID                `json:"property_id"`
	RoomID             uuid.UUID                `json:"room_id"`
	ReservationID      uuid.NullUUID            `json:"reservation_id"`
	ReservationItemID  uuid.NullUUID            `json:"reservation_item_id"`
	MaintenanceBlockID uuid.NullUUID            `json:"maintenance_block_id"`
	CalendarDate       pgtype.Date              `json:"calendar_date"`
	Status             InventoryInventoryStatus `json:"status"`
	RoomName           string                   `json:"room_name"`
	RoomTypeID         uuid.UUID                `json:"room_type_id"`
}

func (q *Queries) GetTapeChartInventory(ctx context.Context, arg *GetTapeChartInventoryParams) ([]GetTapeChartInventoryRow, error) {
	rows, err := q.db.Query(ctx, getTapeChartInventory, arg.PropertyID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTapeChartInventoryRow
	for rows.Next() {
		var i GetTapeChartInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.RoomID,
			&i.ReservationID,
			&i.ReservationItemID,
			&i.MaintenanceBlockID,
			&i.CalendarDate,
			&i.Status,
			&i.RoomName,
			&i.RoomTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTapeChartMaintenanceBlocks = `-- name: GetTapeChartMaintenanceBlocks :many
SELECT
    mb.id,
    mb.property_id,
    mb.room_id,
    LOWER(mb.block_period)::date AS start_date,
    UPPER(mb.block_period)::date AS end_date,
    mb.reason,
    mb.type,
    mb.created_at,
    mb.updated_at
FROM inventory.maintenance_blocks mb
WHERE mb.property_id = $1
  AND LOWER(mb.block_period)::date < $2::date
  AND UPPER(mb.block_period)::date >= $3::date
  AND mb.deleted_at IS NULL
`

type GetTapeChartMaintenanceBlocksParams struct {
	PropertyID uuid.UUID   `json:"property_id"`
	ToDate     pgtype.Date `json:"to_date"`
	FromDate   pgtype.Date `json:"from_date"`
}

type GetTapeChartMaintenanceBlocksRow struct {
	ID         uuid.UUID                     `json:"id"`
	PropertyID uuid.UUID                     `json:"property_id"`
	RoomID     uuid.UUID                     `json:"room_id"`
	StartDate  pgtype.Date                   `json:"start_date"`
	EndDate    pgtype.Date                   `json:"end_date"`
	Reason     string                        `json:"reason"`
	Type       InventoryMaintenanceBlockType `json:"type"`
	CreatedAt  pgtype.Timestamptz            `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz            `json:"updated_at"`
}

func (q *Queries) GetTapeChartMaintenanceBlocks(ctx context.Context, arg *GetTapeChartMaintenanceBlocksParams) ([]GetTapeChartMaintenanceBlocksRow, error) {
	rows, err := q.db.Query(ctx, getTapeChartMaintenanceBlocks, arg.PropertyID, arg.ToDate, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTapeChartMaintenanceBlocksRow
	for rows.Next() {
		var i GetTapeChartMaintenanceBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.RoomID,
			&i.StartDate,
			&i.EndDate,
			&i.Reason,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTapeChartReservationItems = `-- name: GetTapeChartReservationItems :many
SELECT
    ri.id,
    ri.reservation_id,
    ri.assigned_room_id,
    ri.booked_room_type_id,
    ri.guest_id,
    ri.rate_plan_id,
    ri.stay_period,
    ri.do_not_move,
    ri.base_rate_pence,
    ri.adults_count,
    ri.children_count,
    ri.status,
    ri.version,
    ri.created_at,
    ri.updated_at
FROM operations.reservation_items ri
WHERE ri.reservation_id = ANY($1::uuid[])
  AND ri.deleted_at IS NULL
`

type GetTapeChartReservationItemsRow struct {
	ID               uuid.UUID                        `json:"id"`
	ReservationID    uuid.UUID                        `json:"reservation_id"`
	AssignedRoomID   uuid.NullUUID                    `json:"assigned_room_id"`
	BookedRoomTypeID uuid.UUID                        `json:"booked_room_type_id"`
	GuestID          uuid.NullUUID                    `json:"guest_id"`
	RatePlanID       uuid.NullUUID                    `json:"rate_plan_id"`
	StayPeriod       pgtype.Range[pgtype.Timestamptz] `json:"stay_period"`
	DoNotMove        bool                             `json:"do_not_move"`
	BaseRatePence    int32                            `json:"base_rate_pence"`
	AdultsCount      int32                            `json:"adults_count"`
	ChildrenCount    int32                            `json:"children_count"`
	Status           OperationsReservationItemStatus  `json:"status"`
	Version          int32                            `json:"version"`
	CreatedAt        pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz               `json:"updated_at"`
}

func (q *Queries) GetTapeChartReservationItems(ctx context.Context, reservationIds []uuid.UUID) ([]GetTapeChartReservationItemsRow, error) {
	rows, err := q.db.Query(ctx, getTapeChartReservationItems, reservationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTapeChartReservationItemsRow
	for rows.Next() {
		var i GetTapeChartReservationItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.AssignedRoomID,
			&i.BookedRoomTypeID,
			&i.GuestID,
			&i.RatePlanID,
			&i.StayPeriod,
			&i.DoNotMove,
			&i.BaseRatePence,
			&i.AdultsCount,
			&i.ChildrenCount,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTapeChartReservations = `-- name: GetTapeChartReservations :many
SELECT
    r.id,
    r.property_id,
    r.primary_guest_id,
    CONCAT_WS(' ', g.first_name, g.last_name) AS guest_name,
    r.sequential,
    r.code,
    r.source,
    r.status,
    LOWER(r.stay_period_envelope)::timestamptz AS check_in,
    UPPER(r.stay_period_envelope)::timestamptz AS check_out,
    r.notes,
    r.expires_at,
    r.version,
    r.created_at,
    r.updated_at
FROM operations.reservations r
LEFT JOIN identity.guests g ON g.id = r.primary_guest_id AND g.deleted_at IS NULL
WHERE r.property_id = $1
  AND LOWER(r.stay_period_envelope) < $2::timestamptz
  AND UPPER(r.stay_period_envelope) >= $3::timestamptz
  AND r.deleted_at IS NULL
`

type GetTapeChartReservationsParams struct {
	PropertyID uuid.UUID          `json:"property_id"`
	ToDate     pgtype.Timestamptz `json:"to_date"`
	FromDate   pgtype.Timestamptz `json:"from_date"`
}

type GetTapeChartReservationsRow struct {
	ID             uuid.UUID                   `json:"id"`
	PropertyID     uuid.UUID                   `json:"property_id"`
	PrimaryGuestID uuid.UUID                   `json:"primary_guest_id"`
	GuestName      string                      `json:"guest_name"`
	Sequential     int64                       `json:"sequential"`
	Code           string                      `json:"code"`
	Source         OperationsReservationSource `json:"source"`
	Status         OperationsReservationStatus `json:"status"`
	CheckIn        pgtype.Timestamptz          `json:"check_in"`
	CheckOut       pgtype.Timestamptz          `json:"check_out"`
	Notes          pgtype.Text                 `json:"notes"`
	ExpiresAt      pgtype.Timestamptz          `json:"expires_at"`
	Version        int32                       `json:"version"`
	CreatedAt      pgtype.Timestamptz          `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz          `json:"updated_at"`
}

func (q *Queries) GetTapeChartReservations(ctx context.Context, arg *GetTapeChartReservationsParams) ([]GetTapeChartReservationsRow, error) {
	rows, err := q.db.Query(ctx, getTapeChartReservations, arg.PropertyID, arg.ToDate, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTapeChartReservationsRow
	for rows.Next() {
		var i GetTapeChartReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.PrimaryGuestID,
			&i.GuestName,
			&i.Sequential,
			&i.Code,
			&i.Source,
			&i.Status,
			&i.CheckIn,
			&i.CheckOut,
			&i.Notes,
			&i.ExpiresAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTapeChartRoomTypes = `-- name: GetTapeChartRoomTypes :many
SELECT id, property_id, name, std_occupancy, min_occupancy, max_occupancy, created_at, updated_at
FROM inventory.room_types
WHERE property_id = $1
  AND deleted_at IS NULL
ORDER BY name
`

type GetTapeChartRoomTypesRow struct {
	ID           uuid.UUID          `json:"id"`
	PropertyID   uuid.UUID          `json:"property_id"`
	Name         string             `json:"name"`
	StdOccupancy int32              `json:"std_occupancy"`
	MinOccupancy int32              `json:"min_occupancy"`
	MaxOccupancy int32              `json:"max_occupancy"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTapeChartRoomTypes(ctx context.Context, propertyID uuid.UUID) ([]GetTapeChartRoomTypesRow, error) {
	rows, err := q.db.Query(ctx, getTapeChartRoomTypes, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTapeChartRoomTypesRow
	for rows.Next() {
		var i GetTapeChartRoomTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Name,
			&i.StdOccupancy,
			&i.MinOccupancy,
			&i.MaxOccupancy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTapeChartRooms = `-- name: GetTapeChartRooms :many
SELECT id, property_id, room_type_id, name, housekeeping_status, occupancy_status, created_at, updated_at
FROM inventory.rooms
WHERE property_id = $1
  AND deleted_at IS NULL
ORDER BY room_type_id, name
`

type GetTapeChartRoomsRow struct {
	ID                 uuid.UUID                   `json:"id"`
	PropertyID         uuid.UUID                   `json:"property_id"`
	RoomTypeID         uuid.UUID                   `json:"room_type_id"`
	Name               string                      `json:"name"`
	HousekeepingStatus InventoryHousekeepingStatus `json:"housekeeping_status"`
	OccupancyStatus    InventoryOccupancyStatus    `json:"occupancy_status"`
	CreatedAt          pgtype.Timestamptz          `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz          `json:"updated_at"`
}

func (q *Queries) GetTapeChartRooms(ctx context.Context, propertyID uuid.UUID) ([]GetTapeChartRoomsRow, error) {
	rows, err := q.db.Query(ctx, getTapeChartRooms, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTapeChartRoomsRow
	for rows.Next() {
		var i GetTapeChartRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.RoomTypeID,
			&i.Name,
			&i.HousekeepingStatus,
			&i.OccupancyStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
