package main

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"
)

const tsTmpl = `// Auto-generated by 'make gen-constraints'. Do not edit manually.
// Run 'make gen-constraints' after any schema migration.

export const CONSTRAINTS = {
{{- range .Tables}}
  "{{.Name}}": {
    fields: {
    {{- range .Fields}}
      {{.Name}}: { {{.Props}}{{if and .Props .Jsonb}}, {{end}}{{if .Jsonb}}
        jsonb: {
        {{- range .Jsonb}}
          {{.Key}}: { {{.Props}} },
        {{- end}}
        }{{end}} },
    {{- end}}
    },{{if .Comparisons}}
    comparisons: [
    {{- range .Comparisons}}
      { field: "{{.Field}}", operator: "{{.Operator}}", other: "{{.Other}}" },
    {{- end}}
    ],{{end}}{{if .Notes}}
    notes: [
    {{- range .Notes}}
      "{{js .}}",
    {{- end}}
    ],{{end}}
  },
{{- end}}
} as const;

export type ConstraintTable = keyof typeof CONSTRAINTS;
`

type tsTable struct {
	Name        string
	Fields      []tsTSField
	Comparisons []Comparison
	Notes       []string
}

type tsTSField struct {
	Name  string
	Props string
	Jsonb []tsJsonbEntry
}

type tsJsonbEntry struct {
	Key   string
	Props string
}

func writeTS(cm constraintMap, path string) error {
	tables := make([]string, 0, len(cm))
	for k := range cm {
		tables = append(tables, k)
	}
	sort.Strings(tables)

	var tsTables []tsTable
	for _, table := range tables {
		entry := cm[table]

		var tsFields []tsTSField
		for _, field := range sortedKeys(entry.Fields) {
			fc := entry.Fields[field]
			props := buildTSProps(fc)

			var jsonbEntries []tsJsonbEntry
			for _, subKey := range sortedJsonbKeys(fc.Jsonb) {
				sf := fc.Jsonb[subKey]
				jsonbEntries = append(jsonbEntries, tsJsonbEntry{
					Key:   subKey,
					Props: buildTSJsonbProps(sf),
				})
			}

			if props == "" && len(jsonbEntries) == 0 {
				continue
			}
			tsFields = append(tsFields, tsTSField{Name: field, Props: props, Jsonb: jsonbEntries})
		}

		if len(tsFields) == 0 && len(entry.Comparisons) == 0 && len(entry.Notes) == 0 {
			continue
		}
		tsTables = append(tsTables, tsTable{
			Name:        table,
			Fields:      tsFields,
			Comparisons: entry.Comparisons,
			Notes:       entry.Notes,
		})
	}

	tmpl, err := template.New("ts").Parse(tsTmpl)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, struct{ Tables []tsTable }{tsTables}); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func buildTSProps(fc *FieldConstraint) string {
	var parts []string
	if fc.Required {
		parts = append(parts, "required: true")
	}
	if fc.RequiredWith != "" {
		parts = append(parts, fmt.Sprintf("requiredWith: %q", fc.RequiredWith))
	}
	if fc.ValidRange {
		parts = append(parts, "validRange: true")
	}
	if fc.MaxLength != nil {
		parts = append(parts, fmt.Sprintf("maxLength: %d", *fc.MaxLength))
	}
	if fc.MinLength != nil {
		parts = append(parts, fmt.Sprintf("minLength: %d", *fc.MinLength))
	}
	if fc.ExactLength != nil {
		parts = append(parts, fmt.Sprintf("exactLength: %d", *fc.ExactLength))
	}
	if fc.Min != nil {
		parts = append(parts, fmt.Sprintf("min: %d", *fc.Min))
	}
	if fc.Max != nil {
		parts = append(parts, fmt.Sprintf("max: %d", *fc.Max))
	}
	if fc.Pattern != nil {
		parts = append(parts, fmt.Sprintf("pattern: /%s/", *fc.Pattern))
	}
	return strings.Join(parts, ", ")
}

func buildTSJsonbProps(sf *JsonbSubField) string {
	var parts []string
	if sf.Required {
		parts = append(parts, "required: true")
	}
	if sf.Pattern != nil {
		parts = append(parts, fmt.Sprintf("pattern: /%s/", *sf.Pattern))
	}
	if sf.Min != nil {
		parts = append(parts, fmt.Sprintf("min: %d", *sf.Min))
	}
	if sf.Max != nil {
		parts = append(parts, fmt.Sprintf("max: %d", *sf.Max))
	}
	return strings.Join(parts, ", ")
}
