package main

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strconv"

	"gopkg.in/yaml.v3"
)

func writeYAML(cm constraintMap, path string) error {
	tables := make([]string, 0, len(cm))
	for k := range cm {
		tables = append(tables, k)
	}
	sort.Strings(tables)

	root := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	constraintsKey := &yaml.Node{Kind: yaml.ScalarNode, Value: "constraints"}
	constraintsVal := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}

	for _, table := range tables {
		entry := cm[table]
		tableNode := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}

		if len(entry.Fields) > 0 {
			fieldNames := sortedKeys(entry.Fields)
			fieldsKey := &yaml.Node{Kind: yaml.ScalarNode, Value: "fields"}
			fieldsVal := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}

			for _, field := range fieldNames {
				fc := entry.Fields[field]
				if isEmpty(fc) {
					continue
				}
				fieldNode := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
				appendBoolNode(fieldNode, "required", fc.Required)
				if fc.RequiredWith != "" {
					appendStrNode(fieldNode, "required_with", strPtr(fc.RequiredWith))
				}
				appendBoolNode(fieldNode, "valid_range", fc.ValidRange)
				appendIntNode(fieldNode, "max_length", fc.MaxLength)
				appendIntNode(fieldNode, "min_length", fc.MinLength)
				appendIntNode(fieldNode, "exact_length", fc.ExactLength)
				appendIntNode(fieldNode, "min", fc.Min)
				appendIntNode(fieldNode, "max", fc.Max)
				appendStrNode(fieldNode, "pattern", fc.Pattern)

				if len(fc.Jsonb) > 0 {
					jsonbKey := &yaml.Node{Kind: yaml.ScalarNode, Value: "jsonb"}
					jsonbVal := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
					for _, subKey := range sortedJsonbKeys(fc.Jsonb) {
						sf := fc.Jsonb[subKey]
						sfNode := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
						appendBoolNode(sfNode, "required", sf.Required)
						appendStrNode(sfNode, "pattern", sf.Pattern)
						appendIntNode(sfNode, "min", sf.Min)
						appendIntNode(sfNode, "max", sf.Max)
						jsonbVal.Content = append(jsonbVal.Content,
							&yaml.Node{Kind: yaml.ScalarNode, Value: subKey},
							sfNode,
						)
					}
					fieldNode.Content = append(fieldNode.Content, jsonbKey, jsonbVal)
				}

				fieldsVal.Content = append(fieldsVal.Content,
					&yaml.Node{Kind: yaml.ScalarNode, Value: field},
					fieldNode,
				)
			}
			if len(fieldsVal.Content) > 0 {
				tableNode.Content = append(tableNode.Content, fieldsKey, fieldsVal)
			}
		}

		if len(entry.Comparisons) > 0 {
			cmpKey := &yaml.Node{Kind: yaml.ScalarNode, Value: "comparisons"}
			cmpVal := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
			for _, cmp := range entry.Comparisons {
				item := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
				item.Content = append(item.Content,
					&yaml.Node{Kind: yaml.ScalarNode, Value: "field"},
					&yaml.Node{Kind: yaml.ScalarNode, Value: cmp.Field},
					&yaml.Node{Kind: yaml.ScalarNode, Value: "operator"},
					&yaml.Node{Kind: yaml.ScalarNode, Value: cmp.Operator},
					&yaml.Node{Kind: yaml.ScalarNode, Value: "other"},
					&yaml.Node{Kind: yaml.ScalarNode, Value: cmp.Other},
				)
				cmpVal.Content = append(cmpVal.Content, item)
			}
			tableNode.Content = append(tableNode.Content, cmpKey, cmpVal)
		}

		if len(entry.Notes) > 0 {
			notesKey := &yaml.Node{Kind: yaml.ScalarNode, Value: "notes"}
			notesVal := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
			for _, note := range entry.Notes {
				notesVal.Content = append(notesVal.Content,
					&yaml.Node{Kind: yaml.ScalarNode, Value: note},
				)
			}
			tableNode.Content = append(tableNode.Content, notesKey, notesVal)
		}

		if len(tableNode.Content) == 0 {
			continue
		}
		constraintsVal.Content = append(constraintsVal.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: table},
			tableNode,
		)
	}

	root.Content = append(root.Content, constraintsKey, constraintsVal)
	doc := &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{root}}

	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by 'make gen-constraints'. Do not edit manually.\n")
	buf.WriteString("# Run 'make gen-constraints' after any schema migration.\n\n")

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return fmt.Errorf("encode yaml: %w", err)
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func sortedKeys(m map[string]*FieldConstraint) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedJsonbKeys(m map[string]*JsonbSubField) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func appendBoolNode(parent *yaml.Node, key string, val bool) {
	if !val {
		return
	}
	parent.Content = append(parent.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: key},
		&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: "true"},
	)
}

func appendIntNode(parent *yaml.Node, key string, val *int) {
	if val == nil {
		return
	}
	parent.Content = append(parent.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: key},
		&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: strconv.Itoa(*val)},
	)
}

func appendStrNode(parent *yaml.Node, key string, val *string) {
	if val == nil {
		return
	}
	parent.Content = append(parent.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: key},
		&yaml.Node{Kind: yaml.ScalarNode, Value: *val},
	)
}
