// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplateyop = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Check if the server, database, and redis are alive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Get Server Health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/cmd_server.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/reservations": {
            "get": {
                "description": "Cursor-paginated list of reservations for the property.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "List reservations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_booking.ReservationResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid X-Property-ID or query params",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new reservation with one or more room items.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Create reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Reservation payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_booking.CreateReservationInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.ReservationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "409": {
                        "description": "Resource conflict (e.g. duplicate, version mismatch)",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "501": {
                        "description": "Feature not implemented",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/availability": {
            "get": {
                "description": "Check date-range availability for a room type.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Check room type availability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Room type UUID",
                        "name": "room_type_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_booking.DateAvailability"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid query params",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/{id}": {
            "get": {
                "description": "Fetch a single reservation by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Get reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated: items,guest,none",
                        "name": "include",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.ReservationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Reservation not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Patch reservation-level fields: notes, travel_agent_id, group_id, primary_guest_id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Update reservation metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version for optimistic concurrency",
                        "name": "If-Match",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_booking.UpdateMetadataInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.ReservationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Reservation not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "409": {
                        "description": "Version mismatch",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/{id}/cancel": {
            "post": {
                "description": "Cancel a reservation and all its items. Rejects if any item is checked in.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Cancel reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version for optimistic concurrency",
                        "name": "If-Match",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Cancellation details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_booking.CancelInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.ReservationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Reservation not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "409": {
                        "description": "Version mismatch or checked-in items",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/{id}/checkin": {
            "patch": {
                "description": "Batch check-in all items on a reservation. Returns per-item results.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Check in reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.BatchResult"
                        }
                    },
                    "207": {
                        "description": "Partial success (some items failed)",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.BatchResult"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Reservation not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/{id}/checkout": {
            "patch": {
                "description": "Batch check-out all checked-in items on a reservation.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Check out reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.BatchResult"
                        }
                    },
                    "207": {
                        "description": "Partial success",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.BatchResult"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Reservation not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/{id}/confirm": {
            "post": {
                "description": "Transition reservation from hold to confirmed. Requires attached guest.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Confirm reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version for optimistic concurrency",
                        "name": "If-Match",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated: items,guest,none",
                        "name": "include",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.ReservationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Reservation not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "409": {
                        "description": "Version mismatch or invalid transition",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/{id}/items": {
            "post": {
                "description": "Add a new room item to an existing reservation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Add item to reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version for optimistic concurrency",
                        "name": "If-Match",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Item payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_booking.AddItemInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.ReservationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Reservation not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "409": {
                        "description": "Version mismatch or terminal state",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/{id}/items/{item_id}": {
            "patch": {
                "description": "Update stay period, room type, rate plan, guest counts of a reservation item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Update reservation item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Item UUID",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version for optimistic concurrency",
                        "name": "If-Match",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Updated item fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_booking.CreateItemInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.ReservationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "409": {
                        "description": "Version mismatch",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/{id}/items/{item_id}/assign-room": {
            "patch": {
                "description": "Assign or reassign a physical room to a reservation item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Assign room to item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Item UUID",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version for optimistic concurrency",
                        "name": "If-Match",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Room assignment payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_booking.AssignRoomInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.ItemResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "409": {
                        "description": "Version mismatch or DNM conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/{id}/items/{item_id}/cancel": {
            "post": {
                "description": "Cancel an individual reservation item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Cancel single item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Item UUID",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version for optimistic concurrency",
                        "name": "If-Match",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Cancellation details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_booking.CancelInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.ItemResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "409": {
                        "description": "Version mismatch or invalid transition",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/{id}/items/{item_id}/checkin": {
            "patch": {
                "description": "Check in a single reservation item. Requires assigned room.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Check in single item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Item UUID",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version for optimistic concurrency",
                        "name": "If-Match",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.ItemResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "409": {
                        "description": "Version mismatch or invalid transition or unassigned",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/{id}/items/{item_id}/checkout": {
            "patch": {
                "description": "Check out a single reservation item.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Check out single item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Item UUID",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version for optimistic concurrency",
                        "name": "If-Match",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.ItemResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "409": {
                        "description": "Version mismatch or invalid transition",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/{id}/items/{item_id}/no-show": {
            "patch": {
                "description": "Mark a reservation item as no-show. Must be on or after arrival date.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Mark item as no-show",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Item UUID",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version for optimistic concurrency",
                        "name": "If-Match",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.ItemResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "409": {
                        "description": "Version mismatch or before arrival",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/reservations/{id}/reactivate": {
            "post": {
                "description": "Restore a cancelled reservation to confirmed, reactivate items and inventory.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Reactivate cancelled reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version for optimistic concurrency",
                        "name": "If-Match",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_booking.ReservationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID or X-Property-ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "404": {
                        "description": "Reservation not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "409": {
                        "description": "Version mismatch or invalid transition or past reservation",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        },
        "/v1/sse": {
            "get": {
                "description": "Opens a Server-Sent Events stream for real-time updates",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Realtime"
                ],
                "summary": "Subscribe to real-time SSE events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID from authenticated session",
                        "name": "X-Property-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Property UUID (must match authenticated session)",
                        "name": "property_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE event stream — one ChangeEvent per line"
                    },
                    "400": {
                        "description": "property_id query parameter is required or invalid UUID",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "401": {
                        "description": "No authenticated session",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "403": {
                        "description": "Property access denied",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    },
                    "503": {
                        "description": "SSE at capacity",
                        "schema": {
                            "$ref": "#/definitions/github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cmd_server.HealthResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Server is running"
                },
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/cmd_server.ServiceHealth"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "cmd_server.ServiceHealth": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "latency": {
                    "type": "string",
                    "example": "5ms"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "github_com_lexxcode1_yop-pms_internal_platform_apierror.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "enum": [
                        "NOT_FOUND",
                        "BAD_REQUEST",
                        "CONFLICT",
                        "INTERNAL_ERROR",
                        "UNPROCESSABLE_ENTITY"
                    ]
                },
                "message": {
                    "type": "string"
                },
                "suggestions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_lexxcode1_yop-pms_internal_platform_types.ISO8601Date": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        },
        "internal_booking.AddItemInput": {
            "type": "object"
        },
        "internal_booking.AssignRoomInput": {
            "type": "object",
            "properties": {
                "override_dnm_reason": {
                    "type": "string",
                    "example": "Guest insists on room 101"
                },
                "room_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                }
            }
        },
        "internal_booking.BatchError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "ROOM_UNAVAILABLE"
                },
                "message": {
                    "type": "string",
                    "example": "Room not available on selected dates"
                }
            }
        },
        "internal_booking.BatchResult": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_booking.BatchResultItem"
                    }
                }
            }
        },
        "internal_booking.BatchResultItem": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/internal_booking.BatchError"
                },
                "item_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "reservation_item": {
                    "$ref": "#/definitions/internal_booking.ItemResponse"
                },
                "status": {
                    "description": "\"ok\" | \"failed\"",
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_booking.CancelInput": {
            "type": "object",
            "properties": {
                "fee_override_reason": {
                    "type": "string",
                    "example": "Loyalty member"
                },
                "fee_pence": {
                    "type": "integer",
                    "example": 5000
                },
                "reason_code": {
                    "type": "string",
                    "example": "guest_request"
                },
                "refund_action": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_booking.RefundAction"
                        }
                    ],
                    "example": "original"
                },
                "shorten_stay": {
                    "description": "force-cancel checked-in items (requires reservations:post_checkin_mutate)",
                    "type": "boolean",
                    "example": false
                },
                "waive_fee": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "internal_booking.CancellationIntent": {
            "type": "object",
            "properties": {
                "cancelled_by_user_id": {
                    "type": "string"
                },
                "fee_override_reason": {
                    "type": "string",
                    "example": "Loyalty member"
                },
                "fee_pence": {
                    "type": "integer",
                    "example": 5000
                },
                "reason_code": {
                    "type": "string",
                    "example": "guest_request"
                },
                "refund_action": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_booking.RefundAction"
                        }
                    ],
                    "example": "original"
                },
                "waive_fee": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "internal_booking.CreateItemInput": {
            "type": "object"
        },
        "internal_booking.CreateReservationInput": {
            "type": "object"
        },
        "internal_booking.DateAvailability": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "integer",
                    "example": 1
                },
                "date": {
                    "type": "string",
                    "example": "2026-06-01"
                },
                "reason": {
                    "description": "Reason explains why unavailable (e.g. \"no_rate_configured\"). Empty when available.",
                    "type": "string",
                    "example": "no_rate_configured"
                },
                "total": {
                    "type": "integer",
                    "example": 4
                }
            }
        },
        "internal_booking.GuestInlinePayload": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "jane.doe@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Jane"
                },
                "id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "last_name": {
                    "type": "string",
                    "example": "Doe"
                },
                "phone": {
                    "type": "string",
                    "example": "+441234567890"
                }
            }
        },
        "internal_booking.GuestResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "jane@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Jane"
                },
                "id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "last_name": {
                    "type": "string",
                    "example": "Doe"
                },
                "phone": {
                    "type": "string",
                    "example": "+441234567890"
                },
                "property_id": {
                    "type": "string"
                }
            }
        },
        "internal_booking.ItemResponse": {
            "type": "object",
            "properties": {
                "adults_count": {
                    "type": "integer",
                    "example": 2
                },
                "assigned_room_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "base_rate_pence": {
                    "type": "integer",
                    "example": 15000
                },
                "booked_room_type_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "children_count": {
                    "type": "integer",
                    "example": 0
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "do_not_move": {
                    "type": "boolean",
                    "example": false
                },
                "guest_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "property_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "rate_plan_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "reservation_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_booking.ItemStatus"
                        }
                    ],
                    "example": "booked"
                },
                "stay_period": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_booking.ItemStatus": {
            "type": "string",
            "enum": [
                "booked",
                "checked_in",
                "checked_out",
                "no_show",
                "overstay",
                "cancelled",
                "archived"
            ],
            "x-enum-varnames": [
                "ItemStatusBooked",
                "ItemStatusCheckedIn",
                "ItemStatusCheckedOut",
                "ItemStatusNoShow",
                "ItemStatusOverstay",
                "ItemStatusCancelled",
                "ItemStatusArchived"
            ]
        },
        "internal_booking.RefundAction": {
            "type": "string",
            "enum": [
                "none",
                "original",
                "credit"
            ],
            "x-enum-varnames": [
                "RefundNone",
                "RefundOriginal",
                "RefundCredit"
            ]
        },
        "internal_booking.ReservationResponse": {
            "type": "object",
            "properties": {
                "cancellation_intent": {
                    "$ref": "#/definitions/internal_booking.CancellationIntent"
                },
                "code": {
                    "type": "string",
                    "example": "RES-111213"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "guest": {
                    "$ref": "#/definitions/internal_booking.GuestResponse"
                },
                "id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_booking.ItemResponse"
                    }
                },
                "notes": {
                    "type": "string",
                    "example": "Guest requested top floor"
                },
                "primary_guest_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "property_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "sequential": {
                    "type": "integer",
                    "example": 42
                },
                "source": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_booking.ReservationSource"
                        }
                    ],
                    "example": "internal"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_booking.ReservationStatus"
                        }
                    ],
                    "example": "hold"
                },
                "stay_period_envelope": {
                    "type": "string"
                },
                "travel_agent_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_booking.ReservationSource": {
            "type": "string",
            "enum": [
                "website",
                "internal",
                "ota"
            ],
            "x-enum-varnames": [
                "SourceWebsite",
                "SourceInternal",
                "SourceOTA"
            ]
        },
        "internal_booking.ReservationStatus": {
            "type": "string",
            "enum": [
                "hold",
                "confirmed",
                "checked_in",
                "checked_out",
                "pending_cancellation",
                "cancelled",
                "archived"
            ],
            "x-enum-varnames": [
                "StatusHold",
                "StatusConfirmed",
                "StatusCheckedIn",
                "StatusCheckedOut",
                "StatusPendingCancellation",
                "StatusCancelled",
                "StatusArchived"
            ]
        },
        "internal_booking.UpdateMetadataInput": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "notes": {
                    "type": "string",
                    "example": "Updated contact info"
                },
                "primary_guest_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "travel_agent_id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                }
            }
        }
    }
}`

// SwaggerInfoyop holds exported Swagger Info so clients can modify it
var SwaggerInfoyop = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Yop PMS Backend API",
	Description:      "This is the backend API documentation for Yop PMS.",
	InfoInstanceName: "yop",
	SwaggerTemplate:  docTemplateyop,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoyop.InstanceName(), SwaggerInfoyop)
}
