/** @type {import('@stryker-mutator/api/core').StrykerOptions} */
export default {
	packageManager: 'npm',
	testRunner: 'vitest',
	vitest: {
		configFile: 'vitest.config.ts'
	},
	mutate: [
		'src/routes/tape-chart/**/_utils/**/*.ts',
		'!src/routes/tape-chart/**/_utils/**/*.test.ts',
		'src/lib/helpers/dates.ts',
		'src/lib/api/tape-chart.ts'
	],
	// .svelte-kit is gitignored (generated by `svelte-kit sync`), so Stryker's
	// default git-tracked file set excludes it from the sandbox copy — but
	// tsconfig.json extends .svelte-kit/tsconfig.json, so vitest's esbuild
	// transform can't resolve it without this. Setting `files` switches
	// Stryker from its git-tracked-file default to plain globs (ignoring
	// .gitignore), so .svelte-kit is included. Run `npx svelte-kit sync`
	// first if it doesn't exist yet.
	files: ['**/*', '!node_modules/**', '!.git/**', '!build/**', '!.svelte-kit/output/**'],
	reporters: ['clear-text', 'progress', 'html'],
	coverageAnalysis: 'off',
	// The typescript checker type-checks the whole project via tsconfig.json,
	// including test files that import named exports from .svelte files —
	// that only resolves through svelte-check's language server, not plain
	// tsc, so the checker's dry run fails on files unrelated to what's being
	// mutated here (all plain .ts). Skipping it costs a slower run (no early
	// skip for non-compiling mutants); vitest itself still catches breakage.
	thresholds: {
		high: 80,
		low: 60,
		break: 0
	}
};
